#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AIAction_SimpleLeave

#include "Basic.hpp"

#include "BP_AIAction_SimpleLeave_classes.hpp"
#include "BP_AIAction_SimpleLeave_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_AIAction_SimpleLeave.BP_AIAction_SimpleLeave_C.ForceEndAction
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_AIAction_SimpleLeave_C::ForceEndAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_SimpleLeave_C", "ForceEndAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AIAction_SimpleLeave.BP_AIAction_SimpleLeave_C.ExecuteUbergraph_BP_AIAction_SimpleLeave
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_SimpleLeave_C::ExecuteUbergraph_BP_AIAction_SimpleLeave(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_SimpleLeave_C", "ExecuteUbergraph_BP_AIAction_SimpleLeave");

	Params::BP_AIAction_SimpleLeave_C_ExecuteUbergraph_BP_AIAction_SimpleLeave Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AIAction_SimpleLeave.BP_AIAction_SimpleLeave_C.ActionTick
// (Event, Public, BlueprintEvent)
// Parameters:
// class APawn*                            ControlledPawn_ActionTick                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   DeltaSeconds_ActionTick                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AIAction_SimpleLeave_C::ActionTick(class APawn* ControlledPawn_ActionTick, float DeltaSeconds_ActionTick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AIAction_SimpleLeave_C", "ActionTick");

	Params::BP_AIAction_SimpleLeave_C_ActionTick Parms{};

	Parms.ControlledPawn_ActionTick = ControlledPawn_ActionTick;
	Parms.DeltaSeconds_ActionTick = DeltaSeconds_ActionTick;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
