#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HUDDispatchParameter_KeyConfig

#include "Basic.hpp"

#include "InputCore_structs.hpp"
#include "Pal_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
