#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalQuestBlock_TutorialMeal

#include "Basic.hpp"

#include "BP_PalQuestBlock_TutorialMeal_classes.hpp"
#include "BP_PalQuestBlock_TutorialMeal_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_PalQuestBlock_TutorialMeal.BP_PalQuestBlock_TutorialMeal_C.GetDescriptionText
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText*                            OutText                                                (Parm, OutParm)

void UBP_PalQuestBlock_TutorialMeal_C::GetDescriptionText(class FText* OutText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PalQuestBlock_TutorialMeal_C", "GetDescriptionText");

	Params::BP_PalQuestBlock_TutorialMeal_C_GetDescriptionText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutText != nullptr)
		*OutText = std::move(Parms.OutText);
}


SDK_NAMESPACE_END
