#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ReturnOtomoSphereComponent

#include "Basic.hpp"

#include "BP_ReturnOtomoSphereComponent_classes.hpp"


SDK_NAMESPACE_START

// Function BP_ReturnOtomoSphereComponent.BP_ReturnOtomoSphereComponent_C.DeleteSelf
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_ReturnOtomoSphereComponent_C::DeleteSelf()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReturnOtomoSphereComponent_C", "DeleteSelf");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
