#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_PalUIThrowObjectNoneMessageType

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum E_PalUIThrowObjectNoneMessageType.E_PalUIThrowObjectNoneMessageType
// NumValues: 0x0005
enum class E_PalUIThrowObjectNoneMessageType : uint8
{
	NewEnumerator2                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator3                           = 3,
	E_MAX                                    = 4,
};

SDK_NAMESPACE_END
