#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EquipmentSelectListBlock

#include "Basic.hpp"

#include "WBP_EquipmentSelectListBlock_classes.hpp"
#include "WBP_EquipmentSelectListBlock_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_EquipmentSelectListBlock.WBP_EquipmentSelectListBlock_C.GetFocusTarget
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget**                         NewParam_GetFocusTarget                                (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_EquipmentSelectListBlock_C::GetFocusTarget(class UWidget** NewParam_GetFocusTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EquipmentSelectListBlock_C", "GetFocusTarget");

	Params::WBP_EquipmentSelectListBlock_C_GetFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam_GetFocusTarget != nullptr)
		*NewParam_GetFocusTarget = Parms.NewParam_GetFocusTarget;
}


// Function WBP_EquipmentSelectListBlock.WBP_EquipmentSelectListBlock_C.GetAllItemSlotButtons
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class UWBP_PalItemSlotButtonBase_C*>*slotButtons_GetAllItemSlotButtons                      (Parm, OutParm, ContainsInstancedReference)

void UWBP_EquipmentSelectListBlock_C::GetAllItemSlotButtons(TArray<class UWBP_PalItemSlotButtonBase_C*>* slotButtons_GetAllItemSlotButtons)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EquipmentSelectListBlock_C", "GetAllItemSlotButtons");

	Params::WBP_EquipmentSelectListBlock_C_GetAllItemSlotButtons Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (slotButtons_GetAllItemSlotButtons != nullptr)
		*slotButtons_GetAllItemSlotButtons = std::move(Parms.slotButtons_GetAllItemSlotButtons);
}


// Function WBP_EquipmentSelectListBlock.WBP_EquipmentSelectListBlock_C.EditCreatedSlotWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_PalItemSlotButtonBase_C*     createdSlotWidget_EditCreatedSlotWidget                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UWidget**                         editedWidget_EditCreatedSlotWidget                     (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_EquipmentSelectListBlock_C::EditCreatedSlotWidget(class UWBP_PalItemSlotButtonBase_C* createdSlotWidget_EditCreatedSlotWidget, class UWidget** editedWidget_EditCreatedSlotWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EquipmentSelectListBlock_C", "EditCreatedSlotWidget");

	Params::WBP_EquipmentSelectListBlock_C_EditCreatedSlotWidget Parms{};

	Parms.createdSlotWidget_EditCreatedSlotWidget = createdSlotWidget_EditCreatedSlotWidget;

	UObject::ProcessEvent(Func, &Parms);

	if (editedWidget_EditCreatedSlotWidget != nullptr)
		*editedWidget_EditCreatedSlotWidget = Parms.editedWidget_EditCreatedSlotWidget;
}


SDK_NAMESPACE_END
