#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionArchitecture_Player

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ActionInteractBase_Player_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionArchitecture_Player.BP_ActionArchitecture_Player_C
// 0x0020 (0x01B0 - 0x0190)
class UBP_ActionArchitecture_Player_C final : public UBP_ActionInteractBase_Player_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ActionArchitecture_Player_C;     // 0x0190(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   FlagName;                                          // 0x0198(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 HammerActor;                                       // 0x01A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ActionArchitecture_Player(int32 EntryPoint);
	void OnBeginAction();
	void OnEndAction();
	void OnMontageEnd();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionArchitecture_Player_C">();
	}
	static class UBP_ActionArchitecture_Player_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionArchitecture_Player_C>();
	}
};
static_assert(alignof(UBP_ActionArchitecture_Player_C) == 0x000010, "Wrong alignment on UBP_ActionArchitecture_Player_C");
static_assert(sizeof(UBP_ActionArchitecture_Player_C) == 0x0001B0, "Wrong size on UBP_ActionArchitecture_Player_C");
static_assert(offsetof(UBP_ActionArchitecture_Player_C, UberGraphFrame_BP_ActionArchitecture_Player_C) == 0x000190, "Member 'UBP_ActionArchitecture_Player_C::UberGraphFrame_BP_ActionArchitecture_Player_C' has a wrong offset!");
static_assert(offsetof(UBP_ActionArchitecture_Player_C, FlagName) == 0x000198, "Member 'UBP_ActionArchitecture_Player_C::FlagName' has a wrong offset!");
static_assert(offsetof(UBP_ActionArchitecture_Player_C, HammerActor) == 0x0001A0, "Member 'UBP_ActionArchitecture_Player_C::HammerActor' has a wrong offset!");

}

