#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ArenaSequencer

#include "Basic.hpp"

#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ArenaSequencer.BP_ArenaSequencer_C
// 0x0000 (0x0158 - 0x0158)
class UBP_ArenaSequencer_C final : public UPalArenaSequencer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ArenaSequencer_C">();
	}
	static class UBP_ArenaSequencer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ArenaSequencer_C>();
	}
};
static_assert(alignof(UBP_ArenaSequencer_C) == 0x000008, "Wrong alignment on UBP_ArenaSequencer_C");
static_assert(sizeof(UBP_ArenaSequencer_C) == 0x000158, "Wrong size on UBP_ArenaSequencer_C");

}

