#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Action_NPC_GiantClubAttack

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Action_NPC_MeleeAttack_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Action_NPC_GiantClubAttack.BP_Action_NPC_GiantClubAttack_C
// 0x0010 (0x0160 - 0x0150)
class UBP_Action_NPC_GiantClubAttack_C final : public UBP_Action_NPC_MeleeAttack_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Action_NPC_GiantClubAttack_C;    // 0x0150(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   CameraShake;                                       // 0x0158(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Action_NPC_GiantClubAttack(int32 EntryPoint);
	void OnBeginAction();
	void OnBlendOut_CFE0CA6A45DC574AD72A9C9E56E021A6(class FName NotifyName);
	void OnCompleted_CFE0CA6A45DC574AD72A9C9E56E021A6(class FName NotifyName);
	void OnInterrupted_CFE0CA6A45DC574AD72A9C9E56E021A6(class FName NotifyName);
	void OnNotifyBegin_CFE0CA6A45DC574AD72A9C9E56E021A6(class FName NotifyName);
	void OnNotifyEnd_CFE0CA6A45DC574AD72A9C9E56E021A6(class FName NotifyName);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Action_NPC_GiantClubAttack_C">();
	}
	static class UBP_Action_NPC_GiantClubAttack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Action_NPC_GiantClubAttack_C>();
	}
};
static_assert(alignof(UBP_Action_NPC_GiantClubAttack_C) == 0x000010, "Wrong alignment on UBP_Action_NPC_GiantClubAttack_C");
static_assert(sizeof(UBP_Action_NPC_GiantClubAttack_C) == 0x000160, "Wrong size on UBP_Action_NPC_GiantClubAttack_C");
static_assert(offsetof(UBP_Action_NPC_GiantClubAttack_C, UberGraphFrame_BP_Action_NPC_GiantClubAttack_C) == 0x000150, "Member 'UBP_Action_NPC_GiantClubAttack_C::UberGraphFrame_BP_Action_NPC_GiantClubAttack_C' has a wrong offset!");
static_assert(offsetof(UBP_Action_NPC_GiantClubAttack_C, CameraShake) == 0x000158, "Member 'UBP_Action_NPC_GiantClubAttack_C::CameraShake' has a wrong offset!");

}

