#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionAirDash_Right

#include "Basic.hpp"

#include "BP_ActionAirDashBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActionAirDash_Right.BP_ActionAirDash_Right_C
// 0x0000 (0x0250 - 0x0250)
class UBP_ActionAirDash_Right_C final : public UBP_ActionAirDashBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ActionAirDash_Right_C">();
	}
	static class UBP_ActionAirDash_Right_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActionAirDash_Right_C>();
	}
};
static_assert(alignof(UBP_ActionAirDash_Right_C) == 0x000010, "Wrong alignment on UBP_ActionAirDash_Right_C");
static_assert(sizeof(UBP_ActionAirDash_Right_C) == 0x000250, "Wrong size on UBP_ActionAirDash_Right_C");

}

