#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Action_Grappling

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Pal_structs.hpp"


namespace SDK::Params
{

// Function BP_Action_Grappling.BP_Action_Grappling_C.DisableShooter
// 0x0028 (0x0028 - 0x0000)
struct BP_Action_Grappling_C_DisableShooter final
{
public:
	bool                                          Disable;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalShooterFlagContainerPriority              Priority;                                          // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalShooterComponent*                   Shooter;                                           // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalShooterComponent*                   CallFunc_GetComponentByClass_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_Grappling_C_DisableShooter) == 0x000008, "Wrong alignment on BP_Action_Grappling_C_DisableShooter");
static_assert(sizeof(BP_Action_Grappling_C_DisableShooter) == 0x000028, "Wrong size on BP_Action_Grappling_C_DisableShooter");
static_assert(offsetof(BP_Action_Grappling_C_DisableShooter, Disable) == 0x000000, "Member 'BP_Action_Grappling_C_DisableShooter::Disable' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_DisableShooter, Priority) == 0x000001, "Member 'BP_Action_Grappling_C_DisableShooter::Priority' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_DisableShooter, Shooter) == 0x000008, "Member 'BP_Action_Grappling_C_DisableShooter::Shooter' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_DisableShooter, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'BP_Action_Grappling_C_DisableShooter::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_DisableShooter, CallFunc_GetActionCharacter_ReturnValue) == 0x000018, "Member 'BP_Action_Grappling_C_DisableShooter::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_DisableShooter, CallFunc_GetComponentByClass_ReturnValue) == 0x000020, "Member 'BP_Action_Grappling_C_DisableShooter::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");

// Function BP_Action_Grappling.BP_Action_Grappling_C.EndProcess
// 0x0018 (0x0018 - 0x0000)
struct BP_Action_Grappling_C_EndProcess final
{
public:
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalCharacterMovementComponent*         CallFunc_GetPalCharacterMovementComponent_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsClimbing_ReturnValue;                   // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_Grappling_C_EndProcess) == 0x000008, "Wrong alignment on BP_Action_Grappling_C_EndProcess");
static_assert(sizeof(BP_Action_Grappling_C_EndProcess) == 0x000018, "Wrong size on BP_Action_Grappling_C_EndProcess");
static_assert(offsetof(BP_Action_Grappling_C_EndProcess, CallFunc_GetActionCharacter_ReturnValue) == 0x000000, "Member 'BP_Action_Grappling_C_EndProcess::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_EndProcess, CallFunc_GetPalCharacterMovementComponent_ReturnValue) == 0x000008, "Member 'BP_Action_Grappling_C_EndProcess::CallFunc_GetPalCharacterMovementComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_EndProcess, CallFunc_IsClimbing_ReturnValue) == 0x000010, "Member 'BP_Action_Grappling_C_EndProcess::CallFunc_IsClimbing_ReturnValue' has a wrong offset!");

// Function BP_Action_Grappling.BP_Action_Grappling_C.ExecuteUbergraph_BP_Action_Grappling
// 0x0004 (0x0004 - 0x0000)
struct BP_Action_Grappling_C_ExecuteUbergraph_BP_Action_Grappling final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_Grappling_C_ExecuteUbergraph_BP_Action_Grappling) == 0x000004, "Wrong alignment on BP_Action_Grappling_C_ExecuteUbergraph_BP_Action_Grappling");
static_assert(sizeof(BP_Action_Grappling_C_ExecuteUbergraph_BP_Action_Grappling) == 0x000004, "Wrong size on BP_Action_Grappling_C_ExecuteUbergraph_BP_Action_Grappling");
static_assert(offsetof(BP_Action_Grappling_C_ExecuteUbergraph_BP_Action_Grappling, EntryPoint) == 0x000000, "Member 'BP_Action_Grappling_C_ExecuteUbergraph_BP_Action_Grappling::EntryPoint' has a wrong offset!");

// Function BP_Action_Grappling.BP_Action_Grappling_C.GetOffRide
// 0x0030 (0x0030 - 0x0000)
struct BP_Action_Grappling_C_GetOffRide final
{
public:
	class APalCharacter*                          CallFunc_FindOwnerPalCharacter_ReturnValue;        // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_FindOwnerPalCharacter_ReturnValue_1;      // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalRiderComponent*                     CallFunc_GetComponentByClass_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetOffFromPal_ReturnValue;                // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsRiding_ReturnValue;                     // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_Grappling_C_GetOffRide) == 0x000008, "Wrong alignment on BP_Action_Grappling_C_GetOffRide");
static_assert(sizeof(BP_Action_Grappling_C_GetOffRide) == 0x000030, "Wrong size on BP_Action_Grappling_C_GetOffRide");
static_assert(offsetof(BP_Action_Grappling_C_GetOffRide, CallFunc_FindOwnerPalCharacter_ReturnValue) == 0x000000, "Member 'BP_Action_Grappling_C_GetOffRide::CallFunc_FindOwnerPalCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_GetOffRide, CallFunc_FindOwnerPalCharacter_ReturnValue_1) == 0x000008, "Member 'BP_Action_Grappling_C_GetOffRide::CallFunc_FindOwnerPalCharacter_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_GetOffRide, CallFunc_GetController_ReturnValue) == 0x000010, "Member 'BP_Action_Grappling_C_GetOffRide::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_GetOffRide, CallFunc_HasAuthority_ReturnValue) == 0x000018, "Member 'BP_Action_Grappling_C_GetOffRide::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_GetOffRide, CallFunc_GetComponentByClass_ReturnValue) == 0x000020, "Member 'BP_Action_Grappling_C_GetOffRide::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_GetOffRide, CallFunc_GetOffFromPal_ReturnValue) == 0x000028, "Member 'BP_Action_Grappling_C_GetOffRide::CallFunc_GetOffFromPal_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_GetOffRide, CallFunc_IsRiding_ReturnValue) == 0x000029, "Member 'BP_Action_Grappling_C_GetOffRide::CallFunc_IsRiding_ReturnValue' has a wrong offset!");

// Function BP_Action_Grappling.BP_Action_Grappling_C.TryClime
// 0x0060 (0x0060 - 0x0000)
struct BP_Action_Grappling_C_TryClime final
{
public:
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_1;         // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalCharacterMovementComponent*         CallFunc_GetPalCharacterMovementComponent_ReturnValue; // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalClimbingComponent*                  CallFunc_GetComponentByClass_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetGrapplingMoveEndLocation_ReturnValue;  // 0x0020(0x0018)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TryClimbAfterGrappling_ReturnValue;       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0040(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsNearTwoPoint_ReturnValue;               // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_Grappling_C_TryClime) == 0x000008, "Wrong alignment on BP_Action_Grappling_C_TryClime");
static_assert(sizeof(BP_Action_Grappling_C_TryClime) == 0x000060, "Wrong size on BP_Action_Grappling_C_TryClime");
static_assert(offsetof(BP_Action_Grappling_C_TryClime, CallFunc_GetActionCharacter_ReturnValue) == 0x000000, "Member 'BP_Action_Grappling_C_TryClime::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_TryClime, CallFunc_GetActionCharacter_ReturnValue_1) == 0x000008, "Member 'BP_Action_Grappling_C_TryClime::CallFunc_GetActionCharacter_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_TryClime, CallFunc_GetPalCharacterMovementComponent_ReturnValue) == 0x000010, "Member 'BP_Action_Grappling_C_TryClime::CallFunc_GetPalCharacterMovementComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_TryClime, CallFunc_GetComponentByClass_ReturnValue) == 0x000018, "Member 'BP_Action_Grappling_C_TryClime::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_TryClime, CallFunc_GetGrapplingMoveEndLocation_ReturnValue) == 0x000020, "Member 'BP_Action_Grappling_C_TryClime::CallFunc_GetGrapplingMoveEndLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_TryClime, CallFunc_TryClimbAfterGrappling_ReturnValue) == 0x000038, "Member 'BP_Action_Grappling_C_TryClime::CallFunc_TryClimbAfterGrappling_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_TryClime, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000040, "Member 'BP_Action_Grappling_C_TryClime::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_Grappling_C_TryClime, CallFunc_IsNearTwoPoint_ReturnValue) == 0x000058, "Member 'BP_Action_Grappling_C_TryClime::CallFunc_IsNearTwoPoint_ReturnValue' has a wrong offset!");

}

