#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionDeforest

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_ActionDeforest.BP_ActionDeforest_C.ExecuteUbergraph_BP_ActionDeforest
// 0x02B0 (0x02B0 - 0x0000)
struct BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UAnimMontage* Montage, class FName NotifyName)> K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalGameSetting*                        CallFunc_GetGameSetting_ReturnValue;               // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_DecreaseFullStomachRate_Work_ReturnValue; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_1;         // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalSkeletalMeshComponent*              CallFunc_GetMainMesh_ReturnValue;                  // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           K2Node_CustomEvent_Montage;                        // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName;                     // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_2;         // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalSkeletalMeshComponent*              CallFunc_GetMainMesh_ReturnValue_1;                // 0x0060(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_3;         // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalAnimInstance*                       K2Node_DynamicCast_AsPal_Anim_Instance;            // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalAnimInstance*                       K2Node_DynamicCast_AsPal_Anim_Instance_1;          // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_DynamicCast_AsPlayer_Controller;            // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_4;         // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetController_ReturnValue_1;              // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_5;         // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      K2Node_DynamicCast_AsPlayer_Controller_1;          // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalSkeletalMeshComponent*              CallFunc_GetMainMesh_ReturnValue_2;                // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_6;         // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_GetAllSocketNames_ReturnValue;            // 0x00E8(0x0010)(ReferenceParm)
	class FName                                   CallFunc_Array_Get_Item;                           // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x0104(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_NameName_ReturnValue;            // 0x0105(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_106[0x2];                                      // 0x0106(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10C[0x4];                                      // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_7;         // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_119[0x3];                                      // 0x0119(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_8;         // 0x0120(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_GetDetectableNotifyNames_Array;           // 0x0128(0x0010)(ReferenceParm)
	class UPalActionComponent*                    CallFunc_GetActionComponent_ReturnValue;           // 0x0138(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_141[0x7];                                      // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class AActor>                     CallFunc_GetActionTool_ReturnValue;                // 0x0148(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0150(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x01B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x01B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_AddActorLocalRotation_SweepHitResult;  // 0x01C0(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest) == 0x000010, "Wrong alignment on BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest");
static_assert(sizeof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest) == 0x0002B0, "Wrong size on BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, EntryPoint) == 0x000000, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, Temp_int_Array_Index_Variable) == 0x000004, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetActionCharacter_ReturnValue) == 0x000018, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetGameSetting_ReturnValue) == 0x000020, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetGameSetting_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_DecreaseFullStomachRate_Work_ReturnValue) == 0x000028, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_DecreaseFullStomachRate_Work_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetActionCharacter_ReturnValue_1) == 0x000030, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetActionCharacter_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetMainMesh_ReturnValue) == 0x000038, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetMainMesh_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, K2Node_CustomEvent_Montage) == 0x000040, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::K2Node_CustomEvent_Montage' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, K2Node_CustomEvent_NotifyName) == 0x000048, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::K2Node_CustomEvent_NotifyName' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_IsValid_ReturnValue) == 0x000050, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetActionCharacter_ReturnValue_2) == 0x000058, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetActionCharacter_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetMainMesh_ReturnValue_1) == 0x000060, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetMainMesh_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetActionCharacter_ReturnValue_3) == 0x000068, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetActionCharacter_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetAnimInstance_ReturnValue) == 0x000070, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, K2Node_DynamicCast_AsPal_Anim_Instance) == 0x000078, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::K2Node_DynamicCast_AsPal_Anim_Instance' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, K2Node_DynamicCast_bSuccess) == 0x000080, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, K2Node_DynamicCast_AsPal_Anim_Instance_1) == 0x000088, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::K2Node_DynamicCast_AsPal_Anim_Instance_1' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, K2Node_DynamicCast_bSuccess_1) == 0x000090, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetController_ReturnValue) == 0x000098, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, K2Node_DynamicCast_AsPlayer_Controller) == 0x0000A0, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::K2Node_DynamicCast_AsPlayer_Controller' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, K2Node_DynamicCast_bSuccess_2) == 0x0000A8, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetActionCharacter_ReturnValue_4) == 0x0000B0, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetActionCharacter_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetController_ReturnValue_1) == 0x0000B8, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetActionCharacter_ReturnValue_5) == 0x0000C0, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetActionCharacter_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, K2Node_DynamicCast_AsPlayer_Controller_1) == 0x0000C8, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::K2Node_DynamicCast_AsPlayer_Controller_1' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, K2Node_DynamicCast_bSuccess_3) == 0x0000D0, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetMainMesh_ReturnValue_2) == 0x0000D8, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetMainMesh_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetActionCharacter_ReturnValue_6) == 0x0000E0, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetActionCharacter_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetAllSocketNames_ReturnValue) == 0x0000E8, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetAllSocketNames_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_Array_Get_Item) == 0x0000F8, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_Array_Length_ReturnValue) == 0x000100, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_EqualEqual_NameName_ReturnValue) == 0x000104, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_EqualEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_NotEqual_NameName_ReturnValue) == 0x000105, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_NotEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, Temp_int_Loop_Counter_Variable) == 0x000108, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetActionCharacter_ReturnValue_7) == 0x000110, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetActionCharacter_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_Less_IntInt_ReturnValue) == 0x000118, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_Add_IntInt_ReturnValue) == 0x00011C, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetActionCharacter_ReturnValue_8) == 0x000120, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetActionCharacter_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetDetectableNotifyNames_Array) == 0x000128, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetDetectableNotifyNames_Array' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetActionComponent_ReturnValue) == 0x000138, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetActionComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_Array_Contains_ReturnValue) == 0x000140, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_GetActionTool_ReturnValue) == 0x000148, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_GetActionTool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_MakeTransform_ReturnValue) == 0x000150, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x0001B0, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_FinishSpawningActor_ReturnValue) == 0x0001B8, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest, CallFunc_K2_AddActorLocalRotation_SweepHitResult) == 0x0001C0, "Member 'BP_ActionDeforest_C_ExecuteUbergraph_BP_ActionDeforest::CallFunc_K2_AddActorLocalRotation_SweepHitResult' has a wrong offset!");

// Function BP_ActionDeforest.BP_ActionDeforest_C.GetDetectableNotifyNames
// 0x0030 (0x0030 - 0x0000)
struct BP_ActionDeforest_C_GetDetectableNotifyNames final
{
public:
	TArray<class FName>                           Array;                                             // 0x0000(0x0010)(Parm, OutParm)
	class FName                                   CallFunc_ActionNotify_MiningEndTiming_ReturnValue; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_ActionNotify_MiningImpactTiming_ReturnValue; // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           K2Node_MakeArray_Array;                            // 0x0020(0x0010)(ReferenceParm)
};
static_assert(alignof(BP_ActionDeforest_C_GetDetectableNotifyNames) == 0x000008, "Wrong alignment on BP_ActionDeforest_C_GetDetectableNotifyNames");
static_assert(sizeof(BP_ActionDeforest_C_GetDetectableNotifyNames) == 0x000030, "Wrong size on BP_ActionDeforest_C_GetDetectableNotifyNames");
static_assert(offsetof(BP_ActionDeforest_C_GetDetectableNotifyNames, Array) == 0x000000, "Member 'BP_ActionDeforest_C_GetDetectableNotifyNames::Array' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_GetDetectableNotifyNames, CallFunc_ActionNotify_MiningEndTiming_ReturnValue) == 0x000010, "Member 'BP_ActionDeforest_C_GetDetectableNotifyNames::CallFunc_ActionNotify_MiningEndTiming_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_GetDetectableNotifyNames, CallFunc_ActionNotify_MiningImpactTiming_ReturnValue) == 0x000018, "Member 'BP_ActionDeforest_C_GetDetectableNotifyNames::CallFunc_ActionNotify_MiningImpactTiming_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_GetDetectableNotifyNames, K2Node_MakeArray_Array) == 0x000020, "Member 'BP_ActionDeforest_C_GetDetectableNotifyNames::K2Node_MakeArray_Array' has a wrong offset!");

// Function BP_ActionDeforest.BP_ActionDeforest_C.OnBeginAnimNotify
// 0x0010 (0x0010 - 0x0000)
struct BP_ActionDeforest_C_OnBeginAnimNotify final
{
public:
	class UAnimMontage*                           Montage;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   NotifyName;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ActionDeforest_C_OnBeginAnimNotify) == 0x000008, "Wrong alignment on BP_ActionDeforest_C_OnBeginAnimNotify");
static_assert(sizeof(BP_ActionDeforest_C_OnBeginAnimNotify) == 0x000010, "Wrong size on BP_ActionDeforest_C_OnBeginAnimNotify");
static_assert(offsetof(BP_ActionDeforest_C_OnBeginAnimNotify, Montage) == 0x000000, "Member 'BP_ActionDeforest_C_OnBeginAnimNotify::Montage' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_OnBeginAnimNotify, NotifyName) == 0x000008, "Member 'BP_ActionDeforest_C_OnBeginAnimNotify::NotifyName' has a wrong offset!");

// Function BP_ActionDeforest.BP_ActionDeforest_C.SetHiddenAttachWeapon
// 0x0020 (0x0020 - 0x0000)
struct BP_ActionDeforest_C_SetHiddenAttachWeapon final
{
public:
	bool                                          IsHidden;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalShooterComponent*                   CallFunc_GetComponentByClass_ReturnValue;          // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ActionDeforest_C_SetHiddenAttachWeapon) == 0x000008, "Wrong alignment on BP_ActionDeforest_C_SetHiddenAttachWeapon");
static_assert(sizeof(BP_ActionDeforest_C_SetHiddenAttachWeapon) == 0x000020, "Wrong size on BP_ActionDeforest_C_SetHiddenAttachWeapon");
static_assert(offsetof(BP_ActionDeforest_C_SetHiddenAttachWeapon, IsHidden) == 0x000000, "Member 'BP_ActionDeforest_C_SetHiddenAttachWeapon::IsHidden' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_SetHiddenAttachWeapon, CallFunc_GetActionCharacter_ReturnValue) == 0x000008, "Member 'BP_ActionDeforest_C_SetHiddenAttachWeapon::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_SetHiddenAttachWeapon, CallFunc_GetComponentByClass_ReturnValue) == 0x000010, "Member 'BP_ActionDeforest_C_SetHiddenAttachWeapon::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_SetHiddenAttachWeapon, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'BP_ActionDeforest_C_SetHiddenAttachWeapon::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_ActionDeforest.BP_ActionDeforest_C.TriggerWorkActionAttackIfNeed
// 0x00D0 (0x00D0 - 0x0000)
struct BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed final
{
public:
	const class UAnimMontage*                     Montage;                                           // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   SectionName;                                       // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPalFoliageIdentifiableInfo            FoliageInfo;                                       // 0x0010(0x0030)(Edit, BlueprintVisible, NoDestructor)
	struct FVector                                ImpactWorldLocation;                               // 0x0040(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APalMapObject*                          TargetMapObject;                                   // 0x0058(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, NoDestructor, HasGetValueTypeHash)
	class UPalAnimNotify_WorkActionAttack*        Notify;                                            // 0x0060(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalNetArchive                         CallFunc_GetBlackboard_ReturnValue;                // 0x0078(0x0010)(ConstParm)
	struct FPalFoliageIdentifiableInfo            CallFunc_ReadActionBlackboardDeforest_OutIdentifiableInfo; // 0x0088(0x0030)(NoDestructor)
	const class UAnimNotify*                      CallFunc_GetMontageNotify_ReturnValue;             // 0x00B8(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	const class UPalAnimNotify_WorkActionAttack*  K2Node_DynamicCast_AsPal_Anim_Notify_Work_Action_Attack; // 0x00C0(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed) == 0x000008, "Wrong alignment on BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed");
static_assert(sizeof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed) == 0x0000D0, "Wrong size on BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, Montage) == 0x000000, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::Montage' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, SectionName) == 0x000008, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::SectionName' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, FoliageInfo) == 0x000010, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::FoliageInfo' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, ImpactWorldLocation) == 0x000040, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::ImpactWorldLocation' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, TargetMapObject) == 0x000058, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::TargetMapObject' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, Notify) == 0x000060, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::Notify' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, CallFunc_IsValid_ReturnValue) == 0x000068, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, CallFunc_GetActionCharacter_ReturnValue) == 0x000070, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, CallFunc_GetBlackboard_ReturnValue) == 0x000078, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::CallFunc_GetBlackboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, CallFunc_ReadActionBlackboardDeforest_OutIdentifiableInfo) == 0x000088, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::CallFunc_ReadActionBlackboardDeforest_OutIdentifiableInfo' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, CallFunc_GetMontageNotify_ReturnValue) == 0x0000B8, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::CallFunc_GetMontageNotify_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, K2Node_DynamicCast_AsPal_Anim_Notify_Work_Action_Attack) == 0x0000C0, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::K2Node_DynamicCast_AsPal_Anim_Notify_Work_Action_Attack' has a wrong offset!");
static_assert(offsetof(BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed, K2Node_DynamicCast_bSuccess) == 0x0000C8, "Member 'BP_ActionDeforest_C_TriggerWorkActionAttackIfNeed::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

