#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AINPC_CombatGunState_Aim_Oilrig

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_AINPC_CombatGunState_Aim_Oilrig.BP_AINPC_CombatGunState_Aim_Oilrig_C.ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig
// 0x00B8 (0x00B8 - 0x0000)
struct BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_NPCAIController_C*                  CallFunc_GetControllerRef_NPCAICon;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalNPCAIWeaponHandle*                  CallFunc_GetWeaponHandle_WeaponHandle;             // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetSphereCastRadius_ReturnValue;          // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaTime;                            // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_NPCAIController_C*                  CallFunc_GetControllerRef_NPCAICon_1;              // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetTargetActor_TargetActor;               // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalNPCAIWeaponHandle*                  CallFunc_GetWeaponHandle_WeaponHandle_1;           // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_NPCAIController_C*                  CallFunc_GetControllerRef_NPCAICon_2;              // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalNPCAIWeaponHandle*                  CallFunc_GetWeaponHandle_WeaponHandle_2;           // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_NPCAIController_C*                  CallFunc_GetControllerRef_NPCAICon_3;              // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetSelfActor_SelfActor;                   // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetTargetActor_TargetActor_1;             // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_NPCAIController_C*                  CallFunc_GetControllerRef_NPCAICon_4;              // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LineTraceToTarget_ForAIAttack_ReturnValue; // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_AIAction_NPC_CombatBase_C*          CallFunc_GetCombatAIActionRef_BPAIActionNPCCombat; // 0x0080(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetSelfActor_SelfActor_1;                 // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_MoveToTarget_IsNearTarget;                // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetTargetActor_TargetActor_2;             // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsNearTwoActorWithRootRadius_ReturnValue; // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_A_ImplicitCast;          // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_LineTraceToTarget_ForAIAttack_Radius_ImplicitCast; // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig) == 0x000008, "Wrong alignment on BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig");
static_assert(sizeof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig) == 0x0000B8, "Wrong size on BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, EntryPoint) == 0x000000, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetControllerRef_NPCAICon) == 0x000008, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetControllerRef_NPCAICon' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetWeaponHandle_WeaponHandle) == 0x000010, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetWeaponHandle_WeaponHandle' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetSphereCastRadius_ReturnValue) == 0x000018, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetSphereCastRadius_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000020, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, K2Node_Event_DeltaTime) == 0x000028, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::K2Node_Event_DeltaTime' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetControllerRef_NPCAICon_1) == 0x000030, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetControllerRef_NPCAICon_1' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetTargetActor_TargetActor) == 0x000038, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetTargetActor_TargetActor' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetWeaponHandle_WeaponHandle_1) == 0x000040, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetWeaponHandle_WeaponHandle_1' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetControllerRef_NPCAICon_2) == 0x000048, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetControllerRef_NPCAICon_2' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetWeaponHandle_WeaponHandle_2) == 0x000050, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetWeaponHandle_WeaponHandle_2' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetControllerRef_NPCAICon_3) == 0x000058, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetControllerRef_NPCAICon_3' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetSelfActor_SelfActor) == 0x000060, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetSelfActor_SelfActor' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetTargetActor_TargetActor_1) == 0x000068, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetTargetActor_TargetActor_1' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetControllerRef_NPCAICon_4) == 0x000070, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetControllerRef_NPCAICon_4' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_LineTraceToTarget_ForAIAttack_ReturnValue) == 0x000078, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_LineTraceToTarget_ForAIAttack_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetCombatAIActionRef_BPAIActionNPCCombat) == 0x000080, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetCombatAIActionRef_BPAIActionNPCCombat' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetSelfActor_SelfActor_1) == 0x000088, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetSelfActor_SelfActor_1' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_MoveToTarget_IsNearTarget) == 0x000090, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_MoveToTarget_IsNearTarget' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_GetTargetActor_TargetActor_2) == 0x000098, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_GetTargetActor_TargetActor_2' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_IsNearTwoActorWithRootRadius_ReturnValue) == 0x0000A0, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_IsNearTwoActorWithRootRadius_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_Add_DoubleDouble_A_ImplicitCast) == 0x0000A8, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_Add_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig, CallFunc_LineTraceToTarget_ForAIAttack_Radius_ImplicitCast) == 0x0000B0, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_ExecuteUbergraph_BP_AINPC_CombatGunState_Aim_Oilrig::CallFunc_LineTraceToTarget_ForAIAttack_Radius_ImplicitCast' has a wrong offset!");

// Function BP_AINPC_CombatGunState_Aim_Oilrig.BP_AINPC_CombatGunState_Aim_Oilrig_C.StateTick
// 0x0004 (0x0004 - 0x0000)
struct BP_AINPC_CombatGunState_Aim_Oilrig_C_StateTick final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_AINPC_CombatGunState_Aim_Oilrig_C_StateTick) == 0x000004, "Wrong alignment on BP_AINPC_CombatGunState_Aim_Oilrig_C_StateTick");
static_assert(sizeof(BP_AINPC_CombatGunState_Aim_Oilrig_C_StateTick) == 0x000004, "Wrong size on BP_AINPC_CombatGunState_Aim_Oilrig_C_StateTick");
static_assert(offsetof(BP_AINPC_CombatGunState_Aim_Oilrig_C_StateTick, DeltaTime) == 0x000000, "Member 'BP_AINPC_CombatGunState_Aim_Oilrig_C_StateTick::DeltaTime' has a wrong offset!");

}

