#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AIController_CombatHeli

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AIController_CombatHeli.BP_AIController_CombatHeli_C
// 0x0020 (0x0548 - 0x0528)
class ABP_AIController_CombatHeli_C final : public APalAIController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0528(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector                                SpawnedLocation;                                   // 0x0530(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_AIController_CombatHeli(int32 EntryPoint);
	void On_Dead(const struct FPalDeadInfo& DeadInfo);
	void ReceivePossess(class APawn* PossessedPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AIController_CombatHeli_C">();
	}
	static class ABP_AIController_CombatHeli_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AIController_CombatHeli_C>();
	}
};
static_assert(alignof(ABP_AIController_CombatHeli_C) == 0x000008, "Wrong alignment on ABP_AIController_CombatHeli_C");
static_assert(sizeof(ABP_AIController_CombatHeli_C) == 0x000548, "Wrong size on ABP_AIController_CombatHeli_C");
static_assert(offsetof(ABP_AIController_CombatHeli_C, UberGraphFrame) == 0x000528, "Member 'ABP_AIController_CombatHeli_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_AIController_CombatHeli_C, SpawnedLocation) == 0x000530, "Member 'ABP_AIController_CombatHeli_C::SpawnedLocation' has a wrong offset!");

}

