#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Action_RaidBossSummonChant

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_Action_RaidBossSummonChant.BP_Action_RaidBossSummonChant_C.ExecuteUbergraph_BP_Action_RaidBossSummonChant
// 0x0160 (0x0160 - 0x0000)
struct BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_4;                   // 0x0004(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_3;                   // 0x000C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate;              // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_2;                   // 0x0024(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_1;            // 0x002C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_1;                   // 0x003C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_2;            // 0x0044(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName;                     // 0x0054(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_3;            // 0x005C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable;                                // 0x006C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc_FindMontage_StartAnime;                   // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc_FindMontage_StartAnime_1;                 // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_1;         // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalSkeletalMeshComponent*              CallFunc_GetMainMesh_ReturnValue;                  // 0x0098(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc_FindMontage_StartAnime_2;                 // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc_FindMontage_StartAnime_3;                 // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue; // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_2;         // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc_FindMontage_StartAnime_4;                 // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_3;         // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc_FindMontage_StartAnime_5;                 // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_4;         // 0x00E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x00E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0100(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue;        // 0x0118(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_5;         // 0x0120(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue_6;         // 0x0128(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_4;            // 0x0130(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc_GetCurrentMontage_ReturnValue;            // 0x0140(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc_FindMontage_StartAnime_6;                 // 0x0150(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x015A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant) == 0x000008, "Wrong alignment on BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant");
static_assert(sizeof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant) == 0x000160, "Wrong size on BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, EntryPoint) == 0x000000, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, K2Node_CustomEvent_NotifyName_4) == 0x000004, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::K2Node_CustomEvent_NotifyName_4' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, K2Node_CustomEvent_NotifyName_3) == 0x00000C, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::K2Node_CustomEvent_NotifyName_3' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, K2Node_CreateDelegate_OutputDelegate) == 0x000014, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, K2Node_CustomEvent_NotifyName_2) == 0x000024, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::K2Node_CustomEvent_NotifyName_2' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, K2Node_CreateDelegate_OutputDelegate_1) == 0x00002C, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, K2Node_CustomEvent_NotifyName_1) == 0x00003C, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::K2Node_CustomEvent_NotifyName_1' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, K2Node_CreateDelegate_OutputDelegate_2) == 0x000044, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, K2Node_CustomEvent_NotifyName) == 0x000054, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::K2Node_CustomEvent_NotifyName' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, K2Node_CreateDelegate_OutputDelegate_3) == 0x00005C, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, Temp_name_Variable) == 0x00006C, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_GetActionCharacter_ReturnValue) == 0x000078, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_FindMontage_StartAnime) == 0x000080, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_FindMontage_StartAnime' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_FindMontage_StartAnime_1) == 0x000088, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_FindMontage_StartAnime_1' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_GetActionCharacter_ReturnValue_1) == 0x000090, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_GetActionCharacter_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_GetMainMesh_ReturnValue) == 0x000098, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_GetMainMesh_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_FindMontage_StartAnime_2) == 0x0000A0, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_FindMontage_StartAnime_2' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_FindMontage_StartAnime_3) == 0x0000A8, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_FindMontage_StartAnime_3' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue) == 0x0000B0, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_IsValid_ReturnValue) == 0x0000B8, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_GetActionCharacter_ReturnValue_2) == 0x0000C0, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_GetActionCharacter_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_FindMontage_StartAnime_4) == 0x0000C8, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_FindMontage_StartAnime_4' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_GetActionCharacter_ReturnValue_3) == 0x0000D0, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_GetActionCharacter_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_FindMontage_StartAnime_5) == 0x0000D8, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_FindMontage_StartAnime_5' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_GetActionCharacter_ReturnValue_4) == 0x0000E0, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_GetActionCharacter_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0000E8, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_Add_VectorVector_ReturnValue) == 0x000100, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_SpawnSystemAtLocation_ReturnValue) == 0x000118, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_SpawnSystemAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_GetActionCharacter_ReturnValue_5) == 0x000120, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_GetActionCharacter_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_GetActionCharacter_ReturnValue_6) == 0x000128, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_GetActionCharacter_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, K2Node_CreateDelegate_OutputDelegate_4) == 0x000130, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_GetCurrentMontage_ReturnValue) == 0x000140, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_GetCurrentMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_IsValid_ReturnValue_1) == 0x000148, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_FindMontage_StartAnime_6) == 0x000150, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_FindMontage_StartAnime_6' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_Not_PreBool_ReturnValue) == 0x000158, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000159, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant, CallFunc_BooleanOR_ReturnValue) == 0x00015A, "Member 'BP_Action_RaidBossSummonChant_C_ExecuteUbergraph_BP_Action_RaidBossSummonChant::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

// Function BP_Action_RaidBossSummonChant.BP_Action_RaidBossSummonChant_C.FindMontage
// 0x0030 (0x0030 - 0x0000)
struct BP_Action_RaidBossSummonChant_C_FindMontage final
{
public:
	EPalGeneralMontageType                        MontageKey;                                        // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           StartAnime;                                        // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          CallFunc_GetActionCharacter_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalStaticCharacterParameterComponent*  CallFunc_GetComponentByClass_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           CallFunc_Map_Find_Value;                           // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_RaidBossSummonChant_C_FindMontage) == 0x000008, "Wrong alignment on BP_Action_RaidBossSummonChant_C_FindMontage");
static_assert(sizeof(BP_Action_RaidBossSummonChant_C_FindMontage) == 0x000030, "Wrong size on BP_Action_RaidBossSummonChant_C_FindMontage");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_FindMontage, MontageKey) == 0x000000, "Member 'BP_Action_RaidBossSummonChant_C_FindMontage::MontageKey' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_FindMontage, StartAnime) == 0x000008, "Member 'BP_Action_RaidBossSummonChant_C_FindMontage::StartAnime' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_FindMontage, CallFunc_GetActionCharacter_ReturnValue) == 0x000010, "Member 'BP_Action_RaidBossSummonChant_C_FindMontage::CallFunc_GetActionCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_FindMontage, CallFunc_GetComponentByClass_ReturnValue) == 0x000018, "Member 'BP_Action_RaidBossSummonChant_C_FindMontage::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_FindMontage, CallFunc_Map_Find_Value) == 0x000020, "Member 'BP_Action_RaidBossSummonChant_C_FindMontage::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_FindMontage, CallFunc_Map_Find_ReturnValue) == 0x000028, "Member 'BP_Action_RaidBossSummonChant_C_FindMontage::CallFunc_Map_Find_ReturnValue' has a wrong offset!");

// Function BP_Action_RaidBossSummonChant.BP_Action_RaidBossSummonChant_C.OnBlendOut_BE7A92584840B0EC84580786B9907E36
// 0x0008 (0x0008 - 0x0000)
struct BP_Action_RaidBossSummonChant_C_OnBlendOut_BE7A92584840B0EC84580786B9907E36 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_RaidBossSummonChant_C_OnBlendOut_BE7A92584840B0EC84580786B9907E36) == 0x000004, "Wrong alignment on BP_Action_RaidBossSummonChant_C_OnBlendOut_BE7A92584840B0EC84580786B9907E36");
static_assert(sizeof(BP_Action_RaidBossSummonChant_C_OnBlendOut_BE7A92584840B0EC84580786B9907E36) == 0x000008, "Wrong size on BP_Action_RaidBossSummonChant_C_OnBlendOut_BE7A92584840B0EC84580786B9907E36");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_OnBlendOut_BE7A92584840B0EC84580786B9907E36, NotifyName) == 0x000000, "Member 'BP_Action_RaidBossSummonChant_C_OnBlendOut_BE7A92584840B0EC84580786B9907E36::NotifyName' has a wrong offset!");

// Function BP_Action_RaidBossSummonChant.BP_Action_RaidBossSummonChant_C.OnCompleted_BE7A92584840B0EC84580786B9907E36
// 0x0008 (0x0008 - 0x0000)
struct BP_Action_RaidBossSummonChant_C_OnCompleted_BE7A92584840B0EC84580786B9907E36 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_RaidBossSummonChant_C_OnCompleted_BE7A92584840B0EC84580786B9907E36) == 0x000004, "Wrong alignment on BP_Action_RaidBossSummonChant_C_OnCompleted_BE7A92584840B0EC84580786B9907E36");
static_assert(sizeof(BP_Action_RaidBossSummonChant_C_OnCompleted_BE7A92584840B0EC84580786B9907E36) == 0x000008, "Wrong size on BP_Action_RaidBossSummonChant_C_OnCompleted_BE7A92584840B0EC84580786B9907E36");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_OnCompleted_BE7A92584840B0EC84580786B9907E36, NotifyName) == 0x000000, "Member 'BP_Action_RaidBossSummonChant_C_OnCompleted_BE7A92584840B0EC84580786B9907E36::NotifyName' has a wrong offset!");

// Function BP_Action_RaidBossSummonChant.BP_Action_RaidBossSummonChant_C.OnInterrupted_BE7A92584840B0EC84580786B9907E36
// 0x0008 (0x0008 - 0x0000)
struct BP_Action_RaidBossSummonChant_C_OnInterrupted_BE7A92584840B0EC84580786B9907E36 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_RaidBossSummonChant_C_OnInterrupted_BE7A92584840B0EC84580786B9907E36) == 0x000004, "Wrong alignment on BP_Action_RaidBossSummonChant_C_OnInterrupted_BE7A92584840B0EC84580786B9907E36");
static_assert(sizeof(BP_Action_RaidBossSummonChant_C_OnInterrupted_BE7A92584840B0EC84580786B9907E36) == 0x000008, "Wrong size on BP_Action_RaidBossSummonChant_C_OnInterrupted_BE7A92584840B0EC84580786B9907E36");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_OnInterrupted_BE7A92584840B0EC84580786B9907E36, NotifyName) == 0x000000, "Member 'BP_Action_RaidBossSummonChant_C_OnInterrupted_BE7A92584840B0EC84580786B9907E36::NotifyName' has a wrong offset!");

// Function BP_Action_RaidBossSummonChant.BP_Action_RaidBossSummonChant_C.OnNotifyBegin_BE7A92584840B0EC84580786B9907E36
// 0x0008 (0x0008 - 0x0000)
struct BP_Action_RaidBossSummonChant_C_OnNotifyBegin_BE7A92584840B0EC84580786B9907E36 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_RaidBossSummonChant_C_OnNotifyBegin_BE7A92584840B0EC84580786B9907E36) == 0x000004, "Wrong alignment on BP_Action_RaidBossSummonChant_C_OnNotifyBegin_BE7A92584840B0EC84580786B9907E36");
static_assert(sizeof(BP_Action_RaidBossSummonChant_C_OnNotifyBegin_BE7A92584840B0EC84580786B9907E36) == 0x000008, "Wrong size on BP_Action_RaidBossSummonChant_C_OnNotifyBegin_BE7A92584840B0EC84580786B9907E36");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_OnNotifyBegin_BE7A92584840B0EC84580786B9907E36, NotifyName) == 0x000000, "Member 'BP_Action_RaidBossSummonChant_C_OnNotifyBegin_BE7A92584840B0EC84580786B9907E36::NotifyName' has a wrong offset!");

// Function BP_Action_RaidBossSummonChant.BP_Action_RaidBossSummonChant_C.OnNotifyEnd_BE7A92584840B0EC84580786B9907E36
// 0x0008 (0x0008 - 0x0000)
struct BP_Action_RaidBossSummonChant_C_OnNotifyEnd_BE7A92584840B0EC84580786B9907E36 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Action_RaidBossSummonChant_C_OnNotifyEnd_BE7A92584840B0EC84580786B9907E36) == 0x000004, "Wrong alignment on BP_Action_RaidBossSummonChant_C_OnNotifyEnd_BE7A92584840B0EC84580786B9907E36");
static_assert(sizeof(BP_Action_RaidBossSummonChant_C_OnNotifyEnd_BE7A92584840B0EC84580786B9907E36) == 0x000008, "Wrong size on BP_Action_RaidBossSummonChant_C_OnNotifyEnd_BE7A92584840B0EC84580786B9907E36");
static_assert(offsetof(BP_Action_RaidBossSummonChant_C_OnNotifyEnd_BE7A92584840B0EC84580786B9907E36, NotifyName) == 0x000000, "Member 'BP_Action_RaidBossSummonChant_C_OnNotifyEnd_BE7A92584840B0EC84580786B9907E36::NotifyName' has a wrong offset!");

}

