#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CombatHeliRpidWeaponComponent_FrontMG

#include "Basic.hpp"

#include "BP_CombatHeliRpidWeaponComponent_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CombatHeliRpidWeaponComponent_FrontMG.BP_CombatHeliRpidWeaponComponent_FrontMG_C
// 0x0008 (0x0100 - 0x00F8)
class UBP_CombatHeliRpidWeaponComponent_FrontMG_C final : public UBP_CombatHeliRpidWeaponComponent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_CombatHeliRpidWeaponComponent_FrontMG_C; // 0x00F8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_CombatHeliRpidWeaponComponent_FrontMG(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CombatHeliRpidWeaponComponent_FrontMG_C">();
	}
	static class UBP_CombatHeliRpidWeaponComponent_FrontMG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CombatHeliRpidWeaponComponent_FrontMG_C>();
	}
};
static_assert(alignof(UBP_CombatHeliRpidWeaponComponent_FrontMG_C) == 0x000008, "Wrong alignment on UBP_CombatHeliRpidWeaponComponent_FrontMG_C");
static_assert(sizeof(UBP_CombatHeliRpidWeaponComponent_FrontMG_C) == 0x000100, "Wrong size on UBP_CombatHeliRpidWeaponComponent_FrontMG_C");
static_assert(offsetof(UBP_CombatHeliRpidWeaponComponent_FrontMG_C, UberGraphFrame_BP_CombatHeliRpidWeaponComponent_FrontMG_C) == 0x0000F8, "Member 'UBP_CombatHeliRpidWeaponComponent_FrontMG_C::UberGraphFrame_BP_CombatHeliRpidWeaponComponent_FrontMG_C' has a wrong offset!");

}

