#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HUDDispatchParameter_KeyConfig

#include "Basic.hpp"

#include "BP_HUDDispatchParameter_KeyConfig_classes.hpp"
#include "BP_HUDDispatchParameter_KeyConfig_parameters.hpp"


namespace SDK
{

// Function BP_HUDDispatchParameter_KeyConfig.BP_HUDDispatchParameter_KeyConfig_C.OnKeyChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             ActionName_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FKey                             NewKey                                                 (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// EPalKeyConfigCategory                   InputType_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EPalKeyConfigAxisFilterType             AxisType_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HUDDispatchParameter_KeyConfig_C::OnKeyChanged__DelegateSignature(class FName ActionName_0, const struct FKey& NewKey, EPalKeyConfigCategory InputType_0, EPalKeyConfigAxisFilterType AxisType_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HUDDispatchParameter_KeyConfig_C", "OnKeyChanged__DelegateSignature");

	Params::BP_HUDDispatchParameter_KeyConfig_C_OnKeyChanged__DelegateSignature Parms{};

	Parms.ActionName_0 = ActionName_0;
	Parms.NewKey = std::move(NewKey);
	Parms.InputType_0 = InputType_0;
	Parms.AxisType_0 = AxisType_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

