#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MonsterAIController_NPCOtomo

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "Pal_structs.hpp"


namespace SDK::Params
{

// Function BP_MonsterAIController_NPCOtomo.BP_MonsterAIController_NPCOtomo_C.CheckSwimming
// 0x0190 (0x0190 - 0x0000)
struct BP_MonsterAIController_NPCOtomo_C_CheckSwimming final
{
public:
	double                                        DeltaTime;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0020(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_NPCAIController_Oilrig_C*           K2Node_DynamicCast_AsBP_NPCAIController_Oilrig;    // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalCharacterMovementComponent*         CallFunc_GetComponentByClass_ReturnValue;          // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_1;                 // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult;       // 0x0078(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue;          // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_162[0x6];                                      // 0x0162(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_2;                 // 0x0168(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDead_ReturnValue;                       // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_171[0x7];                                      // 0x0171(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_3;                 // 0x0178(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0181(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_182[0x6];                                      // 0x0182(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming) == 0x000008, "Wrong alignment on BP_MonsterAIController_NPCOtomo_C_CheckSwimming");
static_assert(sizeof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming) == 0x000190, "Wrong size on BP_MonsterAIController_NPCOtomo_C_CheckSwimming");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, DeltaTime) == 0x000000, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::DeltaTime' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000008, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_Add_VectorVector_ReturnValue) == 0x000020, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_IsValid_ReturnValue) == 0x000038, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_GetController_ReturnValue) == 0x000040, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_IsValid_ReturnValue_1) == 0x000048, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, K2Node_DynamicCast_AsBP_NPCAIController_Oilrig) == 0x000050, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::K2Node_DynamicCast_AsBP_NPCAIController_Oilrig' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, K2Node_DynamicCast_bSuccess) == 0x000058, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_K2_GetPawn_ReturnValue) == 0x000060, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_K2_GetPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_GetComponentByClass_ReturnValue) == 0x000068, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_K2_GetPawn_ReturnValue_1) == 0x000070, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_K2_GetPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_K2_SetActorLocation_SweepHitResult) == 0x000078, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_K2_SetActorLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_K2_SetActorLocation_ReturnValue) == 0x000160, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_K2_SetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000161, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_K2_GetPawn_ReturnValue_2) == 0x000168, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_K2_GetPawn_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_IsDead_ReturnValue) == 0x000170, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_IsDead_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_K2_GetPawn_ReturnValue_3) == 0x000178, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_K2_GetPawn_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_IsValid_ReturnValue_2) == 0x000180, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x000181, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_CheckSwimming, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000188, "Member 'BP_MonsterAIController_NPCOtomo_C_CheckSwimming::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");

// Function BP_MonsterAIController_NPCOtomo.BP_MonsterAIController_NPCOtomo_C.ExecuteUbergraph_BP_MonsterAIController_NPCOtomo
// 0x00C0 (0x00C0 - 0x0000)
struct BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FPalDeadInfo& DeadInfo)> K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_PossessedPawn;                        // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalDeadInfo                           K2Node_CustomEvent_DeadInfo;                       // 0x0028(0x0050)(NoDestructor)
	class UPalDamageReactionComponent*            CallFunc_GetComponentByClass_ReturnValue;          // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_1;                 // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalBattleManager*                      CallFunc_GetBattleManager_ReturnValue;             // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_2;                 // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_NPCAIController_Oilrig_C*           K2Node_DynamicCast_AsBP_NPCAIController_Oilrig;    // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_CheckSwimming_DeltaTime_ImplicitCast;     // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo) == 0x000008, "Wrong alignment on BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo");
static_assert(sizeof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo) == 0x0000C0, "Wrong size on BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, EntryPoint) == 0x000000, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, K2Node_Event_DeltaSeconds) == 0x000014, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, K2Node_Event_PossessedPawn) == 0x000018, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::K2Node_Event_PossessedPawn' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, CallFunc_K2_GetPawn_ReturnValue) == 0x000020, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::CallFunc_K2_GetPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, K2Node_CustomEvent_DeadInfo) == 0x000028, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::K2Node_CustomEvent_DeadInfo' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, CallFunc_GetComponentByClass_ReturnValue) == 0x000078, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, CallFunc_K2_GetPawn_ReturnValue_1) == 0x000080, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::CallFunc_K2_GetPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, CallFunc_GetBattleManager_ReturnValue) == 0x000088, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::CallFunc_GetBattleManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, CallFunc_K2_GetPawn_ReturnValue_2) == 0x000090, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::CallFunc_K2_GetPawn_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, CallFunc_GetController_ReturnValue) == 0x000098, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, CallFunc_IsValid_ReturnValue) == 0x0000A0, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, K2Node_DynamicCast_AsBP_NPCAIController_Oilrig) == 0x0000A8, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::K2Node_DynamicCast_AsBP_NPCAIController_Oilrig' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, K2Node_DynamicCast_bSuccess) == 0x0000B0, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo, CallFunc_CheckSwimming_DeltaTime_ImplicitCast) == 0x0000B8, "Member 'BP_MonsterAIController_NPCOtomo_C_ExecuteUbergraph_BP_MonsterAIController_NPCOtomo::CallFunc_CheckSwimming_DeltaTime_ImplicitCast' has a wrong offset!");

// Function BP_MonsterAIController_NPCOtomo.BP_MonsterAIController_NPCOtomo_C.GetLeaderBB
// 0x0020 (0x0020 - 0x0000)
struct BP_MonsterAIController_NPCOtomo_C_GetLeaderBB final
{
public:
	class UBP_PalAIBlackboard_Common_C*           LeaderPalBrackboard;                               // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalAIBlackboardBase*                   CallFunc_GetLeaderPalBlackboard_ReturnValue;       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_PalAIBlackboard_Common_C*           K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common;   // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_NPCOtomo_C_GetLeaderBB) == 0x000008, "Wrong alignment on BP_MonsterAIController_NPCOtomo_C_GetLeaderBB");
static_assert(sizeof(BP_MonsterAIController_NPCOtomo_C_GetLeaderBB) == 0x000020, "Wrong size on BP_MonsterAIController_NPCOtomo_C_GetLeaderBB");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_GetLeaderBB, LeaderPalBrackboard) == 0x000000, "Member 'BP_MonsterAIController_NPCOtomo_C_GetLeaderBB::LeaderPalBrackboard' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_GetLeaderBB, CallFunc_GetLeaderPalBlackboard_ReturnValue) == 0x000008, "Member 'BP_MonsterAIController_NPCOtomo_C_GetLeaderBB::CallFunc_GetLeaderPalBlackboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_GetLeaderBB, K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common) == 0x000010, "Member 'BP_MonsterAIController_NPCOtomo_C_GetLeaderBB::K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_GetLeaderBB, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_MonsterAIController_NPCOtomo_C_GetLeaderBB::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BP_MonsterAIController_NPCOtomo.BP_MonsterAIController_NPCOtomo_C.GetMyBB
// 0x0020 (0x0020 - 0x0000)
struct BP_MonsterAIController_NPCOtomo_C_GetMyBB final
{
public:
	class UBP_PalAIBlackboard_Common_C*           PalBrackboard;                                     // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalAIBlackboardBase*                   CallFunc_GetMyPalBlackboard_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_PalAIBlackboard_Common_C*           K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common;   // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_NPCOtomo_C_GetMyBB) == 0x000008, "Wrong alignment on BP_MonsterAIController_NPCOtomo_C_GetMyBB");
static_assert(sizeof(BP_MonsterAIController_NPCOtomo_C_GetMyBB) == 0x000020, "Wrong size on BP_MonsterAIController_NPCOtomo_C_GetMyBB");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_GetMyBB, PalBrackboard) == 0x000000, "Member 'BP_MonsterAIController_NPCOtomo_C_GetMyBB::PalBrackboard' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_GetMyBB, CallFunc_GetMyPalBlackboard_ReturnValue) == 0x000008, "Member 'BP_MonsterAIController_NPCOtomo_C_GetMyBB::CallFunc_GetMyPalBlackboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_GetMyBB, K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common) == 0x000010, "Member 'BP_MonsterAIController_NPCOtomo_C_GetMyBB::K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_GetMyBB, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_MonsterAIController_NPCOtomo_C_GetMyBB::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BP_MonsterAIController_NPCOtomo.BP_MonsterAIController_NPCOtomo_C.ReceivePossess
// 0x0008 (0x0008 - 0x0000)
struct BP_MonsterAIController_NPCOtomo_C_ReceivePossess final
{
public:
	class APawn*                                  PossessedPawn;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_NPCOtomo_C_ReceivePossess) == 0x000008, "Wrong alignment on BP_MonsterAIController_NPCOtomo_C_ReceivePossess");
static_assert(sizeof(BP_MonsterAIController_NPCOtomo_C_ReceivePossess) == 0x000008, "Wrong size on BP_MonsterAIController_NPCOtomo_C_ReceivePossess");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ReceivePossess, PossessedPawn) == 0x000000, "Member 'BP_MonsterAIController_NPCOtomo_C_ReceivePossess::PossessedPawn' has a wrong offset!");

// Function BP_MonsterAIController_NPCOtomo.BP_MonsterAIController_NPCOtomo_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_MonsterAIController_NPCOtomo_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_NPCOtomo_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_MonsterAIController_NPCOtomo_C_ReceiveTick");
static_assert(sizeof(BP_MonsterAIController_NPCOtomo_C_ReceiveTick) == 0x000004, "Wrong size on BP_MonsterAIController_NPCOtomo_C_ReceiveTick");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_MonsterAIController_NPCOtomo_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_MonsterAIController_NPCOtomo.BP_MonsterAIController_NPCOtomo_C.«¹¿à¤ÙóÈ_2
// 0x0050 (0x0050 - 0x0000)
struct BP_MonsterAIController_NPCOtomo_C__________2 final
{
public:
	struct FPalDeadInfo                           DeadInfo;                                          // 0x0000(0x0050)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(BP_MonsterAIController_NPCOtomo_C__________2) == 0x000008, "Wrong alignment on BP_MonsterAIController_NPCOtomo_C__________2");
static_assert(sizeof(BP_MonsterAIController_NPCOtomo_C__________2) == 0x000050, "Wrong size on BP_MonsterAIController_NPCOtomo_C__________2");
static_assert(offsetof(BP_MonsterAIController_NPCOtomo_C__________2, DeadInfo) == 0x000000, "Member 'BP_MonsterAIController_NPCOtomo_C__________2::DeadInfo' has a wrong offset!");

}

