#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MonsterAIController_Visitor_Guardman

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Pal_structs.hpp"


namespace SDK::Params
{

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.BindArriveEvent
// 0x0008 (0x0008 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_BindArriveEvent final
{
public:
	class UBP_AIAction_Visitor_TravelToBaseCamp_Guardman_C* Action;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_BindArriveEvent) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_BindArriveEvent");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_BindArriveEvent) == 0x000008, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_BindArriveEvent");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_BindArriveEvent, Action) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_BindArriveEvent::Action' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.BindOnInvaderArrivedDelegate
// 0x0010 (0x0010 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_BindOnInvaderArrivedDelegate final
{
public:
	TDelegate<void()>                             Event;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_BindOnInvaderArrivedDelegate) == 0x000004, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_BindOnInvaderArrivedDelegate");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_BindOnInvaderArrivedDelegate) == 0x000010, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_BindOnInvaderArrivedDelegate");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_BindOnInvaderArrivedDelegate, Event) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_BindOnInvaderArrivedDelegate::Event' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.BindWaitFinishEvent
// 0x0008 (0x0008 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_BindWaitFinishEvent final
{
public:
	class UBP_AIAction_Visitor_WaitInBaseCamp_C*  Action;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_BindWaitFinishEvent) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_BindWaitFinishEvent");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_BindWaitFinishEvent) == 0x000008, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_BindWaitFinishEvent");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_BindWaitFinishEvent, Action) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_BindWaitFinishEvent::Action' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman
// 0x01C0 (0x01C0 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FPalDeadInfo& DeadInfo)> K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0024(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0034(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_Event_Event;                                // 0x0044(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  K2Node_Event_PossessedPawn;                        // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          K2Node_DynamicCast_AsPal_Character;                // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APalCharacter*                          K2Node_CustomEvent_InCharacter;                    // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalCharacterOnCompleteInitializeParameterWrapper* CallFunc_GetOnCompleteInitializeParameterDelegate_ReturnValue; // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_1;                 // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalDamageReactionComponent*            CallFunc_GetComponentByClass_ReturnValue;          // 0x0090(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FPalDeadInfo                           K2Node_CustomEvent_DeadInfo_1;                     // 0x0098(0x0050)(NoDestructor)
	class UPalBattleManager*                      CallFunc_GetBattleManager_ReturnValue;             // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_2;                 // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_3;                 // 0x00F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_AIAction_Visitor_WaitInBaseCamp_C*  K2Node_CustomEvent_action_1;                       // 0x0100(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class APalCharacter* InCharacter)> K2Node_CreateDelegate_OutputDelegate_4;            // 0x0108(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalDeadInfo                           K2Node_CustomEvent_DeadInfo;                       // 0x0118(0x0050)(NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_169[0x7];                                      // 0x0169(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_AIAction_Visitor_TravelToBaseCamp_Guardman_C* K2Node_CustomEvent_action;                         // 0x0170(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_PalAIBlackboard_Common_C*           CallFunc_GetMyBB_PalBrackboard;                    // 0x0178(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalVisitorInitParameter               K2Node_Event_InitParam;                            // 0x0180(0x0040)(ConstParm, NoDestructor)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman) == 0x0001C0, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, EntryPoint) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_CreateDelegate_OutputDelegate_2) == 0x000024, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_CreateDelegate_OutputDelegate_3) == 0x000034, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_Event_Event) == 0x000044, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_Event_Event' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_Event_PossessedPawn) == 0x000058, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_Event_PossessedPawn' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, CallFunc_K2_GetPawn_ReturnValue) == 0x000060, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::CallFunc_K2_GetPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_DynamicCast_AsPal_Character) == 0x000068, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_DynamicCast_AsPal_Character' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_DynamicCast_bSuccess) == 0x000070, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_CustomEvent_InCharacter) == 0x000078, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_CustomEvent_InCharacter' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, CallFunc_GetOnCompleteInitializeParameterDelegate_ReturnValue) == 0x000080, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::CallFunc_GetOnCompleteInitializeParameterDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, CallFunc_K2_GetPawn_ReturnValue_1) == 0x000088, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::CallFunc_K2_GetPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, CallFunc_GetComponentByClass_ReturnValue) == 0x000090, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_CustomEvent_DeadInfo_1) == 0x000098, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_CustomEvent_DeadInfo_1' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, CallFunc_GetBattleManager_ReturnValue) == 0x0000E8, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::CallFunc_GetBattleManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, CallFunc_K2_GetPawn_ReturnValue_2) == 0x0000F0, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::CallFunc_K2_GetPawn_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, CallFunc_K2_GetPawn_ReturnValue_3) == 0x0000F8, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::CallFunc_K2_GetPawn_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_CustomEvent_action_1) == 0x000100, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_CustomEvent_action_1' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_CreateDelegate_OutputDelegate_4) == 0x000108, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_CustomEvent_DeadInfo) == 0x000118, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_CustomEvent_DeadInfo' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_SwitchEnum_CmpSuccess) == 0x000168, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_CustomEvent_action) == 0x000170, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_CustomEvent_action' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, CallFunc_GetMyBB_PalBrackboard) == 0x000178, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::CallFunc_GetMyBB_PalBrackboard' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman, K2Node_Event_InitParam) == 0x000180, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ExecuteUbergraph_BP_MonsterAIController_Visitor_Guardman::K2Node_Event_InitParam' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.GetLeaderBB
// 0x0020 (0x0020 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB final
{
public:
	class UBP_PalAIBlackboard_Common_C*           LeaderPalBrackboard;                               // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalAIBlackboardBase*                   CallFunc_GetLeaderPalBlackboard_ReturnValue;       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_PalAIBlackboard_Common_C*           K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common;   // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB) == 0x000020, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB, LeaderPalBrackboard) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB::LeaderPalBrackboard' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB, CallFunc_GetLeaderPalBlackboard_ReturnValue) == 0x000008, "Member 'BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB::CallFunc_GetLeaderPalBlackboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB, K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common) == 0x000010, "Member 'BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB::K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_MonsterAIController_Visitor_Guardman_C_GetLeaderBB::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.GetMyBB
// 0x0020 (0x0020 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_GetMyBB final
{
public:
	class UBP_PalAIBlackboard_Common_C*           PalBrackboard;                                     // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalAIBlackboardBase*                   CallFunc_GetMyPalBlackboard_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_PalAIBlackboard_Common_C*           K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common;   // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_GetMyBB) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_GetMyBB");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_GetMyBB) == 0x000020, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_GetMyBB");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_GetMyBB, PalBrackboard) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_GetMyBB::PalBrackboard' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_GetMyBB, CallFunc_GetMyPalBlackboard_ReturnValue) == 0x000008, "Member 'BP_MonsterAIController_Visitor_Guardman_C_GetMyBB::CallFunc_GetMyPalBlackboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_GetMyBB, K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common) == 0x000010, "Member 'BP_MonsterAIController_Visitor_Guardman_C_GetMyBB::K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_GetMyBB, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_MonsterAIController_Visitor_Guardman_C_GetMyBB::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.OnCombatSquad
// 0x00F8 (0x00F8 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad final
{
public:
	class AActor*                                 TargetActor;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_CopyTargetFromOtherAI_ReturnValue;        // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0018(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_1;                 // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0048(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Vector_Distance_ReturnValue;              // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPalAIActionComponent*                  CallFunc_GetComponentByClass_ReturnValue;          // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0088(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPalAIActionDynamicParameter           K2Node_MakeStruct_PalAIActionDynamicParameter;     // 0x00A0(0x0050)(NoDestructor)
	class UPalAIActionBase*                       CallFunc_SetActionClassParameter_ReturnValue;      // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad) == 0x0000F8, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, TargetActor) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::TargetActor' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_RandomFloatInRange_ReturnValue) == 0x000008, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_CopyTargetFromOtherAI_ReturnValue) == 0x000010, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_CopyTargetFromOtherAI_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000018, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_K2_GetPawn_ReturnValue) == 0x000030, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_K2_GetPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_K2_GetPawn_ReturnValue_1) == 0x000038, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_K2_GetPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000040, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000048, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_Vector_Distance_ReturnValue) == 0x000060, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_Vector_Distance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_GetComponentByClass_ReturnValue) == 0x000068, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_FClamp_ReturnValue) == 0x000070, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_FClamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000078, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000080, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_MakeVector_ReturnValue) == 0x000088, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, K2Node_MakeStruct_PalAIActionDynamicParameter) == 0x0000A0, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::K2Node_MakeStruct_PalAIActionDynamicParameter' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad, CallFunc_SetActionClassParameter_ReturnValue) == 0x0000F0, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnCombatSquad::CallFunc_SetActionClassParameter_ReturnValue' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.OnDeadByVisitorLeader
// 0x0050 (0x0050 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_OnDeadByVisitorLeader final
{
public:
	struct FPalDeadInfo                           DeadInfo;                                          // 0x0000(0x0050)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_OnDeadByVisitorLeader) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_OnDeadByVisitorLeader");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_OnDeadByVisitorLeader) == 0x000050, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_OnDeadByVisitorLeader");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_OnDeadByVisitorLeader, DeadInfo) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_OnDeadByVisitorLeader::DeadInfo' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.ReceivePossess
// 0x0008 (0x0008 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_ReceivePossess final
{
public:
	class APawn*                                  PossessedPawn;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_ReceivePossess) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_ReceivePossess");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_ReceivePossess) == 0x000008, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_ReceivePossess");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ReceivePossess, PossessedPawn) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ReceivePossess::PossessedPawn' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.ReturnSpawnedPoint
// 0x0080 (0x0080 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint final
{
public:
	struct FVector                                GoalLocation_0;                                    // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPalAIActionDynamicParameter           K2Node_MakeStruct_PalAIActionDynamicParameter;     // 0x0018(0x0050)(NoDestructor)
	class UPalAIActionComponent*                  K2Node_DynamicCast_AsPal_AIAction_Component;       // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalAIActionBase*                       CallFunc_SetActionClassParameter_ReturnValue;      // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint) == 0x000080, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint, GoalLocation_0) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint::GoalLocation_0' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint, K2Node_MakeStruct_PalAIActionDynamicParameter) == 0x000018, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint::K2Node_MakeStruct_PalAIActionDynamicParameter' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint, K2Node_DynamicCast_AsPal_AIAction_Component) == 0x000068, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint::K2Node_DynamicCast_AsPal_AIAction_Component' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint, K2Node_DynamicCast_bSuccess) == 0x000070, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint, CallFunc_SetActionClassParameter_ReturnValue) == 0x000078, "Member 'BP_MonsterAIController_Visitor_Guardman_C_ReturnSpawnedPoint::CallFunc_SetActionClassParameter_ReturnValue' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.SetupVisitorLeader
// 0x0060 (0x0060 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader final
{
public:
	class APalCharacter*                          CallFunc_GetSquadLeader_ReturnValue;               // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_NPCAIController_Visitor_C*          K2Node_DynamicCast_AsBP_NPCAIController_Visitor;   // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalDamageReactionComponent*            CallFunc_GetComponentByClass_ReturnValue;          // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class AActor* StartActor)>     K2Node_CreateDelegate_OutputDelegate;              // 0x0028(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalSquad*                              CallFunc_GetSquad_ReturnValue;                     // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0040(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FPalDeadInfo& DeadInfo)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x0050(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader) == 0x000060, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader, CallFunc_GetSquadLeader_ReturnValue) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader::CallFunc_GetSquadLeader_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader, CallFunc_GetController_ReturnValue) == 0x000008, "Member 'BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader, K2Node_DynamicCast_AsBP_NPCAIController_Visitor) == 0x000010, "Member 'BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader::K2Node_DynamicCast_AsBP_NPCAIController_Visitor' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader, CallFunc_GetComponentByClass_ReturnValue) == 0x000020, "Member 'BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader, K2Node_CreateDelegate_OutputDelegate) == 0x000028, "Member 'BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader, CallFunc_GetSquad_ReturnValue) == 0x000038, "Member 'BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader::CallFunc_GetSquad_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader, K2Node_CreateDelegate_OutputDelegate_1) == 0x000040, "Member 'BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader, K2Node_CreateDelegate_OutputDelegate_2) == 0x000050, "Member 'BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorLeader::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.SetupVisitorParameter
// 0x0040 (0x0040 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorParameter final
{
public:
	struct FPalVisitorInitParameter               InitParam;                                         // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorParameter) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorParameter");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorParameter) == 0x000040, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorParameter");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorParameter, InitParam) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_SetupVisitorParameter::InitParam' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.StartReturnToSpawnedPointAction
// 0x0070 (0x0070 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction final
{
public:
	class UBP_PalAIBlackboard_Common_C*           CallFunc_GetMyBB_PalBrackboard;                    // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalAIActionComponent*                  K2Node_DynamicCast_AsPal_AIAction_Component;       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPalAIActionDynamicParameter           K2Node_MakeStruct_PalAIActionDynamicParameter;     // 0x0018(0x0050)(NoDestructor)
	class UPalAIActionBase*                       CallFunc_SetActionClassParameter_ReturnValue;      // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction) == 0x000070, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction, CallFunc_GetMyBB_PalBrackboard) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction::CallFunc_GetMyBB_PalBrackboard' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction, K2Node_DynamicCast_AsPal_AIAction_Component) == 0x000008, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction::K2Node_DynamicCast_AsPal_AIAction_Component' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction, K2Node_MakeStruct_PalAIActionDynamicParameter) == 0x000018, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction::K2Node_MakeStruct_PalAIActionDynamicParameter' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction, CallFunc_SetActionClassParameter_ReturnValue) == 0x000068, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartReturnToSpawnedPointAction::CallFunc_SetActionClassParameter_ReturnValue' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.StartTravelToBaseCamp
// 0x0078 (0x0078 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp final
{
public:
	struct FPalAIActionDynamicParameter           K2Node_MakeStruct_PalAIActionDynamicParameter;     // 0x0000(0x0050)(NoDestructor)
	class UPalAIActionComponent*                  K2Node_DynamicCast_AsPal_AIAction_Component;       // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalAIActionBase*                       CallFunc_SetActionClassParameter_ReturnValue;      // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_AIAction_Visitor_TravelToBaseCamp_Guardman_C* K2Node_DynamicCast_AsBP_AIAction_Visitor_Travel_to_Base_Camp_Guardman; // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp) == 0x000078, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp, K2Node_MakeStruct_PalAIActionDynamicParameter) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp::K2Node_MakeStruct_PalAIActionDynamicParameter' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp, K2Node_DynamicCast_AsPal_AIAction_Component) == 0x000050, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp::K2Node_DynamicCast_AsPal_AIAction_Component' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp, K2Node_DynamicCast_bSuccess) == 0x000058, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp, CallFunc_SetActionClassParameter_ReturnValue) == 0x000060, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp::CallFunc_SetActionClassParameter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp, K2Node_DynamicCast_AsBP_AIAction_Visitor_Travel_to_Base_Camp_Guardman) == 0x000068, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp::K2Node_DynamicCast_AsBP_AIAction_Visitor_Travel_to_Base_Camp_Guardman' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp, K2Node_DynamicCast_bSuccess_1) == 0x000070, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartTravelToBaseCamp::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.StartWaitAction
// 0x0070 (0x0070 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction final
{
public:
	class UPalAIActionComponent*                  CallFunc_GetComponentByClass_ReturnValue;          // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FPalAIActionDynamicParameter           K2Node_MakeStruct_PalAIActionDynamicParameter;     // 0x0008(0x0050)(NoDestructor)
	class UPalAIActionBase*                       CallFunc_SetActionClassParameter_ReturnValue;      // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_AIAction_Visitor_WaitInBaseCamp_C*  K2Node_DynamicCast_AsBP_AIAction_Visitor_Wait_in_Base_Camp; // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction) == 0x000070, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction, CallFunc_GetComponentByClass_ReturnValue) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction, K2Node_MakeStruct_PalAIActionDynamicParameter) == 0x000008, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction::K2Node_MakeStruct_PalAIActionDynamicParameter' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction, CallFunc_SetActionClassParameter_ReturnValue) == 0x000058, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction::CallFunc_SetActionClassParameter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction, K2Node_DynamicCast_AsBP_AIAction_Visitor_Wait_in_Base_Camp) == 0x000060, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction::K2Node_DynamicCast_AsBP_AIAction_Visitor_Wait_in_Base_Camp' has a wrong offset!");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction, K2Node_DynamicCast_bSuccess) == 0x000068, "Member 'BP_MonsterAIController_Visitor_Guardman_C_StartWaitAction::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.«¹¿à¤ÙóÈ_1
// 0x0008 (0x0008 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C__________1 final
{
public:
	class APalCharacter*                          InCharacter;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C__________1) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C__________1");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C__________1) == 0x000008, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C__________1");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C__________1, InCharacter) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C__________1::InCharacter' has a wrong offset!");

// Function BP_MonsterAIController_Visitor_Guardman.BP_MonsterAIController_Visitor_Guardman_C.«¹¿à¤ÙóÈ_OnDead
// 0x0050 (0x0050 - 0x0000)
struct BP_MonsterAIController_Visitor_Guardman_C__________OnDead final
{
public:
	struct FPalDeadInfo                           DeadInfo;                                          // 0x0000(0x0050)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(BP_MonsterAIController_Visitor_Guardman_C__________OnDead) == 0x000008, "Wrong alignment on BP_MonsterAIController_Visitor_Guardman_C__________OnDead");
static_assert(sizeof(BP_MonsterAIController_Visitor_Guardman_C__________OnDead) == 0x000050, "Wrong size on BP_MonsterAIController_Visitor_Guardman_C__________OnDead");
static_assert(offsetof(BP_MonsterAIController_Visitor_Guardman_C__________OnDead, DeadInfo) == 0x000000, "Member 'BP_MonsterAIController_Visitor_Guardman_C__________OnDead::DeadInfo' has a wrong offset!");

}

