#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPCAIWeaponHandle_Oilrig

#include "Basic.hpp"

#include "BP_NPCAIWeaponHandle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NPCAIWeaponHandle_Oilrig.BP_NPCAIWeaponHandle_Oilrig_C
// 0x0000 (0x00E0 - 0x00E0)
class UBP_NPCAIWeaponHandle_Oilrig_C final : public UBP_NPCAIWeaponHandle_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NPCAIWeaponHandle_Oilrig_C">();
	}
	static class UBP_NPCAIWeaponHandle_Oilrig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NPCAIWeaponHandle_Oilrig_C>();
	}
};
static_assert(alignof(UBP_NPCAIWeaponHandle_Oilrig_C) == 0x000008, "Wrong alignment on UBP_NPCAIWeaponHandle_Oilrig_C");
static_assert(sizeof(UBP_NPCAIWeaponHandle_Oilrig_C) == 0x0000E0, "Wrong size on UBP_NPCAIWeaponHandle_Oilrig_C");

}

