#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RaidBossSummonMeteor

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Pal_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_RaidBossSummonMeteor.BP_RaidBossSummonMeteor_C.BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature
// 0x0118 (0x0118 - 0x0000)
struct BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    HitComponent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                NormalImpulse;                                     // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0030(0x00E8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");
static_assert(sizeof(BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature) == 0x000118, "Wrong size on BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, HitComponent) == 0x000000, "Member 'BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::HitComponent' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, NormalImpulse) == 0x000018, "Member 'BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::NormalImpulse' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature, Hit) == 0x000030, "Member 'BP_RaidBossSummonMeteor_C_BndEvt__BP_RaidBossSummonMeteor_SphereCollision_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature::Hit' has a wrong offset!");

// Function BP_RaidBossSummonMeteor.BP_RaidBossSummonMeteor_C.CalcSpawnLocation
// 0x0110 (0x0110 - 0x0000)
struct BP_RaidBossSummonMeteor_C_CalcSpawnLocation final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxNum;                                            // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Location;                                          // 0x0008(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               Rotate;                                            // 0x0020(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	double                                        Radius;                                            // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Rad;                                               // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RadiansToDegrees_ReturnValue;             // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0060(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	double                                        CallFunc_Cos_ReturnValue;                          // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Sin_ReturnValue;                          // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GetPI_ReturnValue;                        // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_2;      // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x00A8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_3;      // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x00C8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x00E0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_B_ImplicitCast;       // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_A_ImplicitCast;       // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeRotator_Yaw_ImplicitCast;             // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation) == 0x000008, "Wrong alignment on BP_RaidBossSummonMeteor_C_CalcSpawnLocation");
static_assert(sizeof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation) == 0x000110, "Wrong size on BP_RaidBossSummonMeteor_C_CalcSpawnLocation");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, Index_0) == 0x000000, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::Index_0' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, MaxNum) == 0x000004, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::MaxNum' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, Location) == 0x000008, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::Location' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, Rotate) == 0x000020, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::Rotate' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, Radius) == 0x000038, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::Radius' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, Rad) == 0x000040, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::Rad' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000048, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Conv_IntToFloat_ReturnValue_1) == 0x00004C, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Conv_IntToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000050, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_RadiansToDegrees_ReturnValue) == 0x000058, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_RadiansToDegrees_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_MakeRotator_ReturnValue) == 0x000060, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Cos_ReturnValue) == 0x000078, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Cos_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000080, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Sin_ReturnValue) == 0x000088, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Sin_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_GetPI_ReturnValue) == 0x000090, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_GetPI_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x000098, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Multiply_DoubleDouble_ReturnValue_2) == 0x0000A0, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Multiply_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_MakeVector_ReturnValue) == 0x0000A8, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Multiply_DoubleDouble_ReturnValue_3) == 0x0000C0, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Multiply_DoubleDouble_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0000C8, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Add_VectorVector_ReturnValue) == 0x0000E0, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Divide_DoubleDouble_B_ImplicitCast) == 0x0000F8, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Divide_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_Divide_DoubleDouble_A_ImplicitCast) == 0x000100, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_Divide_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_CalcSpawnLocation, CallFunc_MakeRotator_Yaw_ImplicitCast) == 0x000108, "Member 'BP_RaidBossSummonMeteor_C_CalcSpawnLocation::CallFunc_MakeRotator_Yaw_ImplicitCast' has a wrong offset!");

// Function BP_RaidBossSummonMeteor.BP_RaidBossSummonMeteor_C.EffectFadeOutLoop
// 0x0048 (0x0048 - 0x0000)
struct BP_RaidBossSummonMeteor_C_EffectFadeOutLoop final
{
public:
	double                                        Timer;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        FadeTime;                                          // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Effect;                                            // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   ParamName;                                         // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCurveFloat*                            Curve;                                             // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_ReturnValue;                // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetFloatValue_InTime_ImplicitCast;        // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop) == 0x000008, "Wrong alignment on BP_RaidBossSummonMeteor_C_EffectFadeOutLoop");
static_assert(sizeof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop) == 0x000048, "Wrong size on BP_RaidBossSummonMeteor_C_EffectFadeOutLoop");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop, Timer) == 0x000000, "Member 'BP_RaidBossSummonMeteor_C_EffectFadeOutLoop::Timer' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop, FadeTime) == 0x000008, "Member 'BP_RaidBossSummonMeteor_C_EffectFadeOutLoop::FadeTime' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop, Effect) == 0x000010, "Member 'BP_RaidBossSummonMeteor_C_EffectFadeOutLoop::Effect' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop, ParamName) == 0x000018, "Member 'BP_RaidBossSummonMeteor_C_EffectFadeOutLoop::ParamName' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop, Curve) == 0x000020, "Member 'BP_RaidBossSummonMeteor_C_EffectFadeOutLoop::Curve' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop, CallFunc_Less_DoubleDouble_ReturnValue) == 0x000028, "Member 'BP_RaidBossSummonMeteor_C_EffectFadeOutLoop::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000030, "Member 'BP_RaidBossSummonMeteor_C_EffectFadeOutLoop::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop, CallFunc_FClamp_ReturnValue) == 0x000038, "Member 'BP_RaidBossSummonMeteor_C_EffectFadeOutLoop::CallFunc_FClamp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop, CallFunc_GetFloatValue_ReturnValue) == 0x000040, "Member 'BP_RaidBossSummonMeteor_C_EffectFadeOutLoop::CallFunc_GetFloatValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_EffectFadeOutLoop, CallFunc_GetFloatValue_InTime_ImplicitCast) == 0x000044, "Member 'BP_RaidBossSummonMeteor_C_EffectFadeOutLoop::CallFunc_GetFloatValue_InTime_ImplicitCast' has a wrong offset!");

// Function BP_RaidBossSummonMeteor.BP_RaidBossSummonMeteor_C.ExecuteUbergraph_BP_RaidBossSummonMeteor
// 0x02D0 (0x02D0 - 0x0000)
struct BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_HitComponent;           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_ComponentBoundEvent_NormalImpulse;          // 0x0038(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_ComponentBoundEvent_Hit;                    // 0x0050(0x00E8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0138(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x0150(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue;        // 0x0168(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0170(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_174[0x4];                                      // 0x0174(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue;          // 0x0188(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x01A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x01B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult;       // 0x01D0(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue;          // 0x02B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B9[0x7];                                      // 0x02B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_B_ImplicitCast;          // 0x02C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x02C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor) == 0x000008, "Wrong alignment on BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor");
static_assert(sizeof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor) == 0x0002D0, "Wrong size on BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, EntryPoint) == 0x000000, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000008, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, K2Node_ComponentBoundEvent_HitComponent) == 0x000020, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::K2Node_ComponentBoundEvent_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, K2Node_ComponentBoundEvent_OtherActor) == 0x000028, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, K2Node_ComponentBoundEvent_OtherComp) == 0x000030, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, K2Node_ComponentBoundEvent_NormalImpulse) == 0x000038, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::K2Node_ComponentBoundEvent_NormalImpulse' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, K2Node_ComponentBoundEvent_Hit) == 0x000050, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::K2Node_ComponentBoundEvent_Hit' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000138, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_K2_GetActorRotation_ReturnValue) == 0x000150, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_K2_GetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_SpawnSystemAtLocation_ReturnValue) == 0x000168, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_SpawnSystemAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, K2Node_Event_DeltaSeconds) == 0x000170, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000178, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000180, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_Conv_DoubleToVector_ReturnValue) == 0x000188, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_Conv_DoubleToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_Multiply_VectorVector_ReturnValue) == 0x0001A0, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_Add_VectorVector_ReturnValue) == 0x0001B8, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_K2_SetActorLocation_SweepHitResult) == 0x0001D0, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_K2_SetActorLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_K2_SetActorLocation_ReturnValue) == 0x0002B8, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_K2_SetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_Add_DoubleDouble_B_ImplicitCast) == 0x0002C0, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_Add_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x0002C8, "Member 'BP_RaidBossSummonMeteor_C_ExecuteUbergraph_BP_RaidBossSummonMeteor::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function BP_RaidBossSummonMeteor.BP_RaidBossSummonMeteor_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_RaidBossSummonMeteor_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RaidBossSummonMeteor_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_RaidBossSummonMeteor_C_ReceiveTick");
static_assert(sizeof(BP_RaidBossSummonMeteor_C_ReceiveTick) == 0x000004, "Wrong size on BP_RaidBossSummonMeteor_C_ReceiveTick");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_RaidBossSummonMeteor_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_RaidBossSummonMeteor.BP_RaidBossSummonMeteor_C.SetupMeteor
// 0x0080 (0x0080 - 0x0000)
struct BP_RaidBossSummonMeteor_C_SetupMeteor final
{
public:
	TMap<struct FPalDataTableRowName_PalMonsterData, int32> NameAndNum;                                        // 0x0000(0x0050)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FVector                                MovementDirection;                                 // 0x0050(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGuid                                  CampID;                                            // 0x0068(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Level;                                             // 0x0078(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DelayTime;                                         // 0x007C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RaidBossSummonMeteor_C_SetupMeteor) == 0x000008, "Wrong alignment on BP_RaidBossSummonMeteor_C_SetupMeteor");
static_assert(sizeof(BP_RaidBossSummonMeteor_C_SetupMeteor) == 0x000080, "Wrong size on BP_RaidBossSummonMeteor_C_SetupMeteor");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SetupMeteor, NameAndNum) == 0x000000, "Member 'BP_RaidBossSummonMeteor_C_SetupMeteor::NameAndNum' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SetupMeteor, MovementDirection) == 0x000050, "Member 'BP_RaidBossSummonMeteor_C_SetupMeteor::MovementDirection' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SetupMeteor, CampID) == 0x000068, "Member 'BP_RaidBossSummonMeteor_C_SetupMeteor::CampID' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SetupMeteor, Level) == 0x000078, "Member 'BP_RaidBossSummonMeteor_C_SetupMeteor::Level' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SetupMeteor, DelayTime) == 0x00007C, "Member 'BP_RaidBossSummonMeteor_C_SetupMeteor::DelayTime' has a wrong offset!");

// Function BP_RaidBossSummonMeteor.BP_RaidBossSummonMeteor_C.SpawnPal
// 0x00D0 (0x00D0 - 0x0000)
struct BP_RaidBossSummonMeteor_C_SpawnPal final
{
public:
	TArray<class FName>                           PalIDList;                                         // 0x0000(0x0010)(Edit, BlueprintVisible)
	int32                                         CurrentIndex;                                      // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Sum;                                               // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_CalcSpawnLocation_Location;               // 0x0030(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_CalcSpawnLocation_Rotate;                 // 0x0048(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UPalRaidBossManager*                    CallFunc_GetRaidBossManager_ReturnValue;           // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalRaidBossComponent*                  CallFunc_FindRaidComponent_ReturnValue;            // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item;                           // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_PalRaidBossComponent_C*             K2Node_DynamicCast_AsBP_Pal_Raid_Boss_Component;   // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x3];                                       // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x3];                                       // 0x0089(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FPalDataTableRowName_PalMonsterData> CallFunc_Map_Keys_Keys;                            // 0x0098(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPalDataTableRowName_PalMonsterData    CallFunc_Array_Get_Item_1;                         // 0x00AC(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B5[0x3];                                       // 0x00B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Map_Find_Value;                           // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C1[0x3];                                       // 0x00C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RaidBossSummonMeteor_C_SpawnPal) == 0x000008, "Wrong alignment on BP_RaidBossSummonMeteor_C_SpawnPal");
static_assert(sizeof(BP_RaidBossSummonMeteor_C_SpawnPal) == 0x0000D0, "Wrong size on BP_RaidBossSummonMeteor_C_SpawnPal");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, PalIDList) == 0x000000, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::PalIDList' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CurrentIndex) == 0x000010, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CurrentIndex' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, Sum) == 0x000014, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::Sum' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, Temp_int_Array_Index_Variable) == 0x000018, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, Temp_int_Loop_Counter_Variable) == 0x00001C, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, Temp_int_Loop_Counter_Variable_1) == 0x000024, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Add_IntInt_ReturnValue_1) == 0x000028, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, Temp_int_Array_Index_Variable_1) == 0x00002C, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_CalcSpawnLocation_Location) == 0x000030, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_CalcSpawnLocation_Location' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_CalcSpawnLocation_Rotate) == 0x000048, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_CalcSpawnLocation_Rotate' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_GetRaidBossManager_ReturnValue) == 0x000060, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_GetRaidBossManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_FindRaidComponent_ReturnValue) == 0x000068, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_FindRaidComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Array_Get_Item) == 0x000070, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, K2Node_DynamicCast_AsBP_Pal_Raid_Boss_Component) == 0x000078, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::K2Node_DynamicCast_AsBP_Pal_Raid_Boss_Component' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, K2Node_DynamicCast_bSuccess) == 0x000080, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Array_Length_ReturnValue) == 0x000084, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Less_IntInt_ReturnValue) == 0x000088, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, Temp_int_Variable) == 0x00008C, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Add_IntInt_ReturnValue_2) == 0x000090, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Map_Keys_Keys) == 0x000098, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Array_Length_ReturnValue_1) == 0x0000A8, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Array_Get_Item_1) == 0x0000AC, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000B4, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Array_Add_ReturnValue) == 0x0000B8, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Map_Find_Value) == 0x0000BC, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Map_Find_ReturnValue) == 0x0000C0, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Add_IntInt_ReturnValue_3) == 0x0000C4, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_Subtract_IntInt_ReturnValue) == 0x0000C8, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RaidBossSummonMeteor_C_SpawnPal, CallFunc_LessEqual_IntInt_ReturnValue) == 0x0000CC, "Member 'BP_RaidBossSummonMeteor_C_SpawnPal::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");

}

