#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WorldSecurityLaw_AttackToPolice

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_WorldSecurityLaw_AttackToPolice.BP_WorldSecurityLaw_AttackToPolice_C
// 0x0000 (0x0040 - 0x0040)
class UBP_WorldSecurityLaw_AttackToPolice_C final : public UPalWorldSecurityLawTrigger_CharacterDamaged
{
public:
	bool Condition(const struct FPalDamageResult& DamageResult, class UPalIndividualCharacterHandle** CriminalHandle);
	void IsPolice(EPalOrganizationType OrganizationType, bool* bCitizen);
	void IsValidCharacterActor(class AActor* Actor, bool* bValid, class UPalCharacterParameterComponent** CharacterParameter);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_WorldSecurityLaw_AttackToPolice_C">();
	}
	static class UBP_WorldSecurityLaw_AttackToPolice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_WorldSecurityLaw_AttackToPolice_C>();
	}
};
static_assert(alignof(UBP_WorldSecurityLaw_AttackToPolice_C) == 0x000008, "Wrong alignment on UBP_WorldSecurityLaw_AttackToPolice_C");
static_assert(sizeof(UBP_WorldSecurityLaw_AttackToPolice_C) == 0x000040, "Wrong size on UBP_WorldSecurityLaw_AttackToPolice_C");

}

