#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalCommonInfo_SaveParameter

#include "Basic.hpp"

#include "WBP_PalSaveParameterDisplayWidget_classes.hpp"
#include "Pal_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PalCommonInfo_SaveParameter.WBP_PalCommonInfo_SaveParameter_C
// 0x0008 (0x06F8 - 0x06F0)
class UWBP_PalCommonInfo_SaveParameter_C final : public UWBP_PalSaveParameterDisplayWidget_C
{
public:
	class UWBP_IngameMenu_PalBox_PalDetail_C*     WBP_IngameMenu_PalBox_PalDetail;                   // 0x06F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void DisplaySaveParameter(const struct FPalIndividualCharacterSaveParameter& DisplayParameter);
	void SetBaseParameter(int32 MeleeAttack, int32 ShotAttack, int32 Defense, int32 Support, int32 Speed);
	void SetElement(EPalElementType Type1, EPalElementType Type2);
	void SetEmpty();
	void SetFoodAmount(int32 FoddAmount);
	void SetGender(EPalGenderType GenderType);
	void SetHP(int32 NowHP, int32 MaxHP);
	void SetHunger(double NowHunger, double MaxHunger);
	void SetLevelAndExp(int32 Level, int64 NowExp, int64 NextEXP, double NowExpRate);
	void SetNickName(const class FString& NickName);
	void SetPassiveSkill(TArray<class FName>& PassiveSkillnameArray);
	void SetRank(int32 Rank);
	void SetSoulRank(int32 SoulRank);
	void SetupAfterDisplayed();
	void SetWaza(TArray<EPalWazaID>& WazaArray);
	void SetWorkSuitability(const TMap<EPalWorkSuitability, int32>& SuitabilityMap);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PalCommonInfo_SaveParameter_C">();
	}
	static class UWBP_PalCommonInfo_SaveParameter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PalCommonInfo_SaveParameter_C>();
	}
};
static_assert(alignof(UWBP_PalCommonInfo_SaveParameter_C) == 0x000008, "Wrong alignment on UWBP_PalCommonInfo_SaveParameter_C");
static_assert(sizeof(UWBP_PalCommonInfo_SaveParameter_C) == 0x0006F8, "Wrong size on UWBP_PalCommonInfo_SaveParameter_C");
static_assert(offsetof(UWBP_PalCommonInfo_SaveParameter_C, WBP_IngameMenu_PalBox_PalDetail) == 0x0006F0, "Member 'UWBP_PalCommonInfo_SaveParameter_C::WBP_IngameMenu_PalBox_PalDetail' has a wrong offset!");

}

