#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalOverallUILayout

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Slate_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.CREATEDELEGATE_PROXYFUNCTION_0
// 0x0001 (0x0001 - 0x0000)
struct WBP_PalOverallUILayout_C_CREATEDELEGATE_PROXYFUNCTION_0 final
{
public:
	EPalUICommonWarningType                       WarningType;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalOverallUILayout_C_CREATEDELEGATE_PROXYFUNCTION_0) == 0x000001, "Wrong alignment on WBP_PalOverallUILayout_C_CREATEDELEGATE_PROXYFUNCTION_0");
static_assert(sizeof(WBP_PalOverallUILayout_C_CREATEDELEGATE_PROXYFUNCTION_0) == 0x000001, "Wrong size on WBP_PalOverallUILayout_C_CREATEDELEGATE_PROXYFUNCTION_0");
static_assert(offsetof(WBP_PalOverallUILayout_C_CREATEDELEGATE_PROXYFUNCTION_0, WarningType) == 0x000000, "Member 'WBP_PalOverallUILayout_C_CREATEDELEGATE_PROXYFUNCTION_0::WarningType' has a wrong offset!");

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.ExecuteUbergraph_WBP_PalOverallUILayout
// 0x04D0 (0x04D0 - 0x0000)
struct WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_Event_TargetWidget;                         // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UWidget>                 CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue; // 0x0030(0x0030)(InstancedReference, UObjectWrapper, HasGetValueTypeHash)
	struct FAnchors                               K2Node_MakeStruct_Anchors;                         // 0x0060(0x0020)(NoDestructor)
	EPalFadeWidgetLayerType                       K2Node_Event_LayerType_1;                          // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x3];                                       // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_4;                  // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_94[0x4];                                       // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                           CallFunc_Map_Find_Value;                           // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnchors                               K2Node_MakeStruct_Anchors_1;                       // 0x00B0(0x0020)(NoDestructor)
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x00D0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FMargin                                K2Node_MakeStruct_Margin_1;                        // 0x00E0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F4[0x4];                                       // 0x00F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPalUICommonItemInfoDisplayData        K2Node_Event_DisplayData;                          // 0x00F8(0x00C8)(ConstParm, ContainsInstancedReference)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x01C1(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_NameName_ReturnValue;            // 0x01C2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01C3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEmpty_ReturnValue_1;                    // 0x01C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C5[0x3];                                      // 0x01C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalAudioWorldSubsystem*                CallFunc_GetWorldSubsystem_ReturnValue;            // 0x01C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalAudioWorldSubsystem*                CallFunc_GetWorldSubsystem_ReturnValue_1;          // 0x01D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EPalUICommonWarningType                       Temp_byte_Variable;                                // 0x01D8(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D9[0x7];                                      // 0x01D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x01E0(0x0040)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_4;                   // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLift_ReturnValue;                       // 0x0229(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_22A[0x6];                                      // 0x022A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UCanvasPanelSlot*                       CallFunc_SlotAsCanvasSlot_ReturnValue;             // 0x0230(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalHUDService*                         CallFunc_GetHUDService_ReturnValue;                // 0x0238(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetMousePositionOnViewport_ReturnValue;   // 0x0240(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_251[0x7];                                      // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CallFunc_Add_Vector2DVector2D_ReturnValue;         // 0x0258(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPalUILiftSlotModel*                    CallFunc_GetLiftSlotModel_ReturnValue;             // 0x0268(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FPalUICommonRewardDisplayData          K2Node_Event_RewardDisplayData;                    // 0x0270(0x0058)(ConstParm)
	class UPalAudioWorldSubsystem*                CallFunc_GetWorldSubsystem_ReturnValue_2;          // 0x02C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x02D0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x02E0(0x0008)(NoDestructor, HasGetValueTypeHash)
	class UWBP_CommonWarning_C*                   CallFunc_SpawnObject_ReturnValue;                  // 0x02E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x02F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x02F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x02F5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F6[0x2];                                      // 0x02F6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_MakeLiteralInt_ReturnValue;               // 0x02F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2FC[0x4];                                      // 0x02FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UCanvasPanel*>                   CallFunc_Map_Values_Values;                        // 0x0300(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UCanvasPanel*                           CallFunc_Array_Get_Item;                           // 0x0310(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue;               // 0x0318(0x0010)(ReferenceParm, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0328(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32C[0x4];                                      // 0x032C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_Array_Get_Item_1;                         // 0x0330(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0338(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_339[0x7];                                      // 0x0339(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_PalFadeWidgetBase_C*               K2Node_DynamicCast_AsWBP_Pal_Fade_Widget_Base;     // 0x0340(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0348(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_349[0x3];                                      // 0x0349(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x034C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalFadeWidgetLayerType                       K2Node_Event_LayerType;                            // 0x0351(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_352[0x6];                                      // 0x0352(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalHUDDispatchParameter_FadeWidget*    K2Node_Event_FadeParameter;                        // 0x0358(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0360(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_361[0x7];                                      // 0x0361(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_Map_Find_Value_1;                         // 0x0368(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x0370(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_371[0x7];                                      // 0x0371(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_PalFadeWidgetBase_C*               CallFunc_Create_ReturnValue;                       // 0x0378(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x0380(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_384[0x4];                                      // 0x0384(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCanvasPanel*                           CallFunc_Map_Find_Value_2;                         // 0x0388(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_2;                   // 0x0390(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_391[0x7];                                      // 0x0391(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCanvasPanelSlot*                       CallFunc_AddChildToCanvas_ReturnValue;             // 0x0398(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue_1;             // 0x03A0(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UWidget*                                CallFunc_Array_Get_Item_2;                         // 0x03B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x03B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x03BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3BD[0x3];                                      // 0x03BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPalUICommonWarningDisplayData         K2Node_Event_WarningDisplayData;                   // 0x03C0(0x0030)(ConstParm)
	struct FGuid                                  K2Node_Event_PreserveID;                           // 0x03F0(0x0010)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_Guid_ReturnValue;                 // 0x0400(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Contains_ReturnValue;                 // 0x0401(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_Guid_ReturnValue_1;               // 0x0402(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0403(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_404[0x4];                                      // 0x0404(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UVerticalBoxSlot*                       CallFunc_AddChildToVerticalBox_ReturnValue;        // 0x0408(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UWidget*>                        CallFunc_GetAllChildren_ReturnValue_2;             // 0x0410(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UWidget*                                CallFunc_Array_Get_Item_3;                         // 0x0420(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_CommonWarning_C*                   K2Node_DynamicCast_AsWBP_Common_Warning;           // 0x0428(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0430(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_431[0x3];                                      // 0x0431(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x0434(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0438(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Remove_ReturnValue;                   // 0x0439(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_43A[0x6];                                      // 0x043A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_CommonWarning_C*                   CallFunc_Map_Find_Value_3;                         // 0x0440(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_3;                   // 0x0448(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_449[0x3];                                      // 0x0449(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPalSoundOptions                       K2Node_MakeStruct_PalSoundOptions;                 // 0x044C(0x0004)(NoDestructor)
	int32                                         CallFunc_PlaySound_ReturnValue;                    // 0x0450(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Contains_ReturnValue_1;               // 0x0454(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_455[0x3];                                      // 0x0455(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0458(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_45C[0x4];                                      // 0x045C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 CallFunc_Map_Values_Values_1;                      // 0x0460(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Get_Item_4;                         // 0x0470(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x0474(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x0478(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_479[0x3];                                      // 0x0479(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x047C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                           CallFunc_SpawnObject_ReturnValue_1;                // 0x0480(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x0488(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_48C[0x4];                                      // 0x048C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCanvasPanelSlot*                       CallFunc_AddChildToCanvas_ReturnValue_1;           // 0x0490(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Conv_IntToByte_ReturnValue;               // 0x0498(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x0499(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_GetEnumeratorValueFromIndex_ReturnValue;  // 0x049A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49B[0x1];                                      // 0x049B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x049C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x04A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPalUICommonWarningType                       K2Node_CustomEvent_WarningType;                    // 0x04A4(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Conv_IntToByte_ReturnValue_1;             // 0x04A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_GetValidValue_ReturnValue;                // 0x04A6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x04A7(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Find_ReturnValue;                   // 0x04A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_6;                // 0x04AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4AD[0x3];                                      // 0x04AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Find_ReturnValue_1;                 // 0x04B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Map_Find_Value_4;                         // 0x04B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_4;                   // 0x04B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Remove_ReturnValue_1;                 // 0x04B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BA[0x2];                                      // 0x04BA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(EPalUICommonWarningType WarningType)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x04BC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout) == 0x000008, "Wrong alignment on WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout");
static_assert(sizeof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout) == 0x0004D0, "Wrong size on WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, EntryPoint) == 0x000000, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Array_Index_Variable) == 0x000004, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Loop_Counter_Variable_1) == 0x000010, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Add_IntInt_ReturnValue_1) == 0x000014, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Array_Index_Variable_1) == 0x000018, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Loop_Counter_Variable_2) == 0x00001C, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Add_IntInt_ReturnValue_2) == 0x000020, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Array_Index_Variable_2) == 0x000024, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_Event_TargetWidget) == 0x000028, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_Event_TargetWidget' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue) == 0x000030, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_MakeStruct_Anchors) == 0x000060, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_MakeStruct_Anchors' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_Event_LayerType_1) == 0x000080, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_Event_LayerType_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Loop_Counter_Variable_3) == 0x000084, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Add_IntInt_ReturnValue_3) == 0x000088, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Loop_Counter_Variable_4) == 0x00008C, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Loop_Counter_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Add_IntInt_ReturnValue_4) == 0x000090, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetLocalPlayerController_ReturnValue) == 0x000098, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Find_Value) == 0x0000A0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Find_ReturnValue) == 0x0000A8, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_MakeStruct_Anchors_1) == 0x0000B0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_MakeStruct_Anchors_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_MakeStruct_Margin) == 0x0000D0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_MakeStruct_Margin_1) == 0x0000E0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_MakeStruct_Margin_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Array_Index_Variable_3) == 0x0000F0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_Event_DisplayData) == 0x0000F8, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_Event_DisplayData' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_IsValid_ReturnValue) == 0x0001C0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_IsEmpty_ReturnValue) == 0x0001C1, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_IsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_NotEqual_NameName_ReturnValue) == 0x0001C2, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_NotEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_IsValid_ReturnValue_1) == 0x0001C3, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_IsEmpty_ReturnValue_1) == 0x0001C4, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_IsEmpty_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetWorldSubsystem_ReturnValue) == 0x0001C8, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetWorldSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetWorldSubsystem_ReturnValue_1) == 0x0001D0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetWorldSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_byte_Variable) == 0x0001D8, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_Event_MyGeometry) == 0x0001E0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_Event_InDeltaTime) == 0x000220, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Array_Index_Variable_4) == 0x000224, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Array_Index_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_IsValid_ReturnValue_2) == 0x000228, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_IsLift_ReturnValue) == 0x000229, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_IsLift_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_SlotAsCanvasSlot_ReturnValue) == 0x000230, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_SlotAsCanvasSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetHUDService_ReturnValue) == 0x000238, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetHUDService_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetMousePositionOnViewport_ReturnValue) == 0x000240, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetMousePositionOnViewport_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_IsValid_ReturnValue_3) == 0x000250, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Add_Vector2DVector2D_ReturnValue) == 0x000258, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Add_Vector2DVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetLiftSlotModel_ReturnValue) == 0x000268, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetLiftSlotModel_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_Event_RewardDisplayData) == 0x000270, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_Event_RewardDisplayData' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetWorldSubsystem_ReturnValue_2) == 0x0002C8, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetWorldSubsystem_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_CreateDelegate_OutputDelegate) == 0x0002D0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x0002E0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_SpawnObject_ReturnValue) == 0x0002E8, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Length_ReturnValue) == 0x0002F0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_RemoveItem_ReturnValue) == 0x0002F4, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x0002F5, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_MakeLiteralInt_ReturnValue) == 0x0002F8, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_MakeLiteralInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Values_Values) == 0x000300, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Values_Values' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Get_Item) == 0x000310, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetAllChildren_ReturnValue) == 0x000318, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetAllChildren_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Length_ReturnValue_1) == 0x000328, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Get_Item_1) == 0x000330, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Less_IntInt_ReturnValue) == 0x000338, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_DynamicCast_AsWBP_Pal_Fade_Widget_Base) == 0x000340, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_DynamicCast_AsWBP_Pal_Fade_Widget_Base' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_DynamicCast_bSuccess) == 0x000348, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Length_ReturnValue_2) == 0x00034C, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Less_IntInt_ReturnValue_1) == 0x000350, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_Event_LayerType) == 0x000351, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_Event_LayerType' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_Event_FadeParameter) == 0x000358, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_Event_FadeParameter' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_IsValid_ReturnValue_4) == 0x000360, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Find_Value_1) == 0x000368, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Find_ReturnValue_1) == 0x000370, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Create_ReturnValue) == 0x000378, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_AddUnique_ReturnValue) == 0x000380, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Find_Value_2) == 0x000388, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Find_Value_2' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Find_ReturnValue_2) == 0x000390, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Find_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_AddChildToCanvas_ReturnValue) == 0x000398, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_AddChildToCanvas_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetAllChildren_ReturnValue_1) == 0x0003A0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetAllChildren_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Get_Item_2) == 0x0003B0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Length_ReturnValue_3) == 0x0003B8, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Less_IntInt_ReturnValue_2) == 0x0003BC, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_Event_WarningDisplayData) == 0x0003C0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_Event_WarningDisplayData' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_Event_PreserveID) == 0x0003F0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_Event_PreserveID' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_IsValid_Guid_ReturnValue) == 0x000400, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_IsValid_Guid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Contains_ReturnValue) == 0x000401, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_IsValid_Guid_ReturnValue_1) == 0x000402, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_IsValid_Guid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_SwitchEnum_CmpSuccess) == 0x000403, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_AddChildToVerticalBox_ReturnValue) == 0x000408, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_AddChildToVerticalBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetAllChildren_ReturnValue_2) == 0x000410, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetAllChildren_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Get_Item_3) == 0x000420, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_DynamicCast_AsWBP_Common_Warning) == 0x000428, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_DynamicCast_AsWBP_Common_Warning' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_DynamicCast_bSuccess_1) == 0x000430, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Length_ReturnValue_4) == 0x000434, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Less_IntInt_ReturnValue_3) == 0x000438, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Remove_ReturnValue) == 0x000439, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Remove_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Find_Value_3) == 0x000440, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Find_Value_3' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Find_ReturnValue_3) == 0x000448, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Find_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_MakeStruct_PalSoundOptions) == 0x00044C, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_MakeStruct_PalSoundOptions' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_PlaySound_ReturnValue) == 0x000450, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_PlaySound_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Contains_ReturnValue_1) == 0x000454, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Contains_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Add_ReturnValue) == 0x000458, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Values_Values_1) == 0x000460, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Values_Values_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Get_Item_4) == 0x000470, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Length_ReturnValue_5) == 0x000474, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Length_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Less_IntInt_ReturnValue_4) == 0x000478, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Variable) == 0x00047C, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_SpawnObject_ReturnValue_1) == 0x000480, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_SpawnObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Add_IntInt_ReturnValue_5) == 0x000488, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_AddChildToCanvas_ReturnValue_1) == 0x000490, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_AddChildToCanvas_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Conv_IntToByte_ReturnValue) == 0x000498, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Conv_IntToByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Less_IntInt_ReturnValue_5) == 0x000499, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetEnumeratorValueFromIndex_ReturnValue) == 0x00049A, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetEnumeratorValueFromIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Conv_ByteToInt_ReturnValue) == 0x00049C, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, Temp_int_Variable_1) == 0x0004A0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_CustomEvent_WarningType) == 0x0004A4, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_CustomEvent_WarningType' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Conv_IntToByte_ReturnValue_1) == 0x0004A5, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Conv_IntToByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_GetValidValue_ReturnValue) == 0x0004A6, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_GetValidValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x0004A7, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Find_ReturnValue) == 0x0004A8, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Less_IntInt_ReturnValue_6) == 0x0004AC, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Less_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Array_Find_ReturnValue_1) == 0x0004B0, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Array_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Find_Value_4) == 0x0004B4, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Find_Value_4' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Find_ReturnValue_4) == 0x0004B8, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Find_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, CallFunc_Map_Remove_ReturnValue_1) == 0x0004B9, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::CallFunc_Map_Remove_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout, K2Node_CreateDelegate_OutputDelegate_1) == 0x0004BC, "Member 'WBP_PalOverallUILayout_C_ExecuteUbergraph_WBP_PalOverallUILayout::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.FadeIn
// 0x0001 (0x0001 - 0x0000)
struct WBP_PalOverallUILayout_C_FadeIn final
{
public:
	EPalFadeWidgetLayerType                       LayerType;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalOverallUILayout_C_FadeIn) == 0x000001, "Wrong alignment on WBP_PalOverallUILayout_C_FadeIn");
static_assert(sizeof(WBP_PalOverallUILayout_C_FadeIn) == 0x000001, "Wrong size on WBP_PalOverallUILayout_C_FadeIn");
static_assert(offsetof(WBP_PalOverallUILayout_C_FadeIn, LayerType) == 0x000000, "Member 'WBP_PalOverallUILayout_C_FadeIn::LayerType' has a wrong offset!");

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.FadeOut
// 0x0010 (0x0010 - 0x0000)
struct WBP_PalOverallUILayout_C_FadeOut final
{
public:
	EPalFadeWidgetLayerType                       LayerType;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalHUDDispatchParameter_FadeWidget*    FadeParameter;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalOverallUILayout_C_FadeOut) == 0x000008, "Wrong alignment on WBP_PalOverallUILayout_C_FadeOut");
static_assert(sizeof(WBP_PalOverallUILayout_C_FadeOut) == 0x000010, "Wrong size on WBP_PalOverallUILayout_C_FadeOut");
static_assert(offsetof(WBP_PalOverallUILayout_C_FadeOut, LayerType) == 0x000000, "Member 'WBP_PalOverallUILayout_C_FadeOut::LayerType' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_FadeOut, FadeParameter) == 0x000008, "Member 'WBP_PalOverallUILayout_C_FadeOut::FadeParameter' has a wrong offset!");

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.HideCommonWarning
// 0x0010 (0x0010 - 0x0000)
struct WBP_PalOverallUILayout_C_HideCommonWarning final
{
public:
	struct FGuid                                  PreserveID;                                        // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalOverallUILayout_C_HideCommonWarning) == 0x000004, "Wrong alignment on WBP_PalOverallUILayout_C_HideCommonWarning");
static_assert(sizeof(WBP_PalOverallUILayout_C_HideCommonWarning) == 0x000010, "Wrong size on WBP_PalOverallUILayout_C_HideCommonWarning");
static_assert(offsetof(WBP_PalOverallUILayout_C_HideCommonWarning, PreserveID) == 0x000000, "Member 'WBP_PalOverallUILayout_C_HideCommonWarning::PreserveID' has a wrong offset!");

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.OnWarningClear
// 0x0001 (0x0001 - 0x0000)
struct WBP_PalOverallUILayout_C_OnWarningClear final
{
public:
	EPalUICommonWarningType                       WarningType;                                       // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalOverallUILayout_C_OnWarningClear) == 0x000001, "Wrong alignment on WBP_PalOverallUILayout_C_OnWarningClear");
static_assert(sizeof(WBP_PalOverallUILayout_C_OnWarningClear) == 0x000001, "Wrong size on WBP_PalOverallUILayout_C_OnWarningClear");
static_assert(offsetof(WBP_PalOverallUILayout_C_OnWarningClear, WarningType) == 0x000000, "Member 'WBP_PalOverallUILayout_C_OnWarningClear::WarningType' has a wrong offset!");

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.ShowCommonItemInfo
// 0x00C8 (0x00C8 - 0x0000)
struct WBP_PalOverallUILayout_C_ShowCommonItemInfo final
{
public:
	struct FPalUICommonItemInfoDisplayData        DisplayData;                                       // 0x0000(0x00C8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(WBP_PalOverallUILayout_C_ShowCommonItemInfo) == 0x000008, "Wrong alignment on WBP_PalOverallUILayout_C_ShowCommonItemInfo");
static_assert(sizeof(WBP_PalOverallUILayout_C_ShowCommonItemInfo) == 0x0000C8, "Wrong size on WBP_PalOverallUILayout_C_ShowCommonItemInfo");
static_assert(offsetof(WBP_PalOverallUILayout_C_ShowCommonItemInfo, DisplayData) == 0x000000, "Member 'WBP_PalOverallUILayout_C_ShowCommonItemInfo::DisplayData' has a wrong offset!");

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.ShowCommonReward
// 0x0058 (0x0058 - 0x0000)
struct WBP_PalOverallUILayout_C_ShowCommonReward final
{
public:
	struct FPalUICommonRewardDisplayData          RewardDisplayData;                                 // 0x0000(0x0058)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(WBP_PalOverallUILayout_C_ShowCommonReward) == 0x000008, "Wrong alignment on WBP_PalOverallUILayout_C_ShowCommonReward");
static_assert(sizeof(WBP_PalOverallUILayout_C_ShowCommonReward) == 0x000058, "Wrong size on WBP_PalOverallUILayout_C_ShowCommonReward");
static_assert(offsetof(WBP_PalOverallUILayout_C_ShowCommonReward, RewardDisplayData) == 0x000000, "Member 'WBP_PalOverallUILayout_C_ShowCommonReward::RewardDisplayData' has a wrong offset!");

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.ShowCommonWarning
// 0x0030 (0x0030 - 0x0000)
struct WBP_PalOverallUILayout_C_ShowCommonWarning final
{
public:
	struct FPalUICommonWarningDisplayData         WarningDisplayData;                                // 0x0000(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(WBP_PalOverallUILayout_C_ShowCommonWarning) == 0x000008, "Wrong alignment on WBP_PalOverallUILayout_C_ShowCommonWarning");
static_assert(sizeof(WBP_PalOverallUILayout_C_ShowCommonWarning) == 0x000030, "Wrong size on WBP_PalOverallUILayout_C_ShowCommonWarning");
static_assert(offsetof(WBP_PalOverallUILayout_C_ShowCommonWarning, WarningDisplayData) == 0x000000, "Member 'WBP_PalOverallUILayout_C_ShowCommonWarning::WarningDisplayData' has a wrong offset!");

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.ShowFocusCursor
// 0x0008 (0x0008 - 0x0000)
struct WBP_PalOverallUILayout_C_ShowFocusCursor final
{
public:
	class UWidget*                                TargetWidget;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalOverallUILayout_C_ShowFocusCursor) == 0x000008, "Wrong alignment on WBP_PalOverallUILayout_C_ShowFocusCursor");
static_assert(sizeof(WBP_PalOverallUILayout_C_ShowFocusCursor) == 0x000008, "Wrong size on WBP_PalOverallUILayout_C_ShowFocusCursor");
static_assert(offsetof(WBP_PalOverallUILayout_C_ShowFocusCursor, TargetWidget) == 0x000000, "Member 'WBP_PalOverallUILayout_C_ShowFocusCursor::TargetWidget' has a wrong offset!");

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.Tick
// 0x0048 (0x0048 - 0x0000)
struct WBP_PalOverallUILayout_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0040(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalOverallUILayout_C_Tick) == 0x000008, "Wrong alignment on WBP_PalOverallUILayout_C_Tick");
static_assert(sizeof(WBP_PalOverallUILayout_C_Tick) == 0x000048, "Wrong size on WBP_PalOverallUILayout_C_Tick");
static_assert(offsetof(WBP_PalOverallUILayout_C_Tick, MyGeometry) == 0x000000, "Member 'WBP_PalOverallUILayout_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_Tick, InDeltaTime) == 0x000040, "Member 'WBP_PalOverallUILayout_C_Tick::InDeltaTime' has a wrong offset!");

// Function WBP_PalOverallUILayout.WBP_PalOverallUILayout_C.UpdateCursor
// 0x00D0 (0x00D0 - 0x0000)
struct WBP_PalOverallUILayout_C_UpdateCursor final
{
public:
	class UCanvasPanelSlot*                       CallFunc_SlotAsCanvasSlot_ReturnValue;             // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue; // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidSoftObjectReference_ReturnValue;   // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                K2Node_DynamicCast_AsWidget;                       // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelWidget*                           CallFunc_GetParent_ReturnValue;                    // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              CallFunc_GetCachedGeometry_ReturnValue;            // 0x0038(0x0040)(ConstParm, IsPlainOldData, NoDestructor)
	struct FVector2D                              CallFunc_GetLocalSize_ReturnValue;                 // 0x0078(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_LocalToViewport_PixelPosition;            // 0x0088(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_LocalToViewport_ViewportPosition;         // 0x0098(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_Multiply_Vector2DVector2D_ReturnValue;    // 0x00A8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_X;                          // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_Y;                          // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast; // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast; // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalOverallUILayout_C_UpdateCursor) == 0x000008, "Wrong alignment on WBP_PalOverallUILayout_C_UpdateCursor");
static_assert(sizeof(WBP_PalOverallUILayout_C_UpdateCursor) == 0x0000D0, "Wrong size on WBP_PalOverallUILayout_C_UpdateCursor");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_SlotAsCanvasSlot_ReturnValue) == 0x000000, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_SlotAsCanvasSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue) == 0x000010, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_IsValidSoftObjectReference_ReturnValue) == 0x000018, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_IsValidSoftObjectReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, K2Node_DynamicCast_AsWidget) == 0x000020, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::K2Node_DynamicCast_AsWidget' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_GetParent_ReturnValue) == 0x000030, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_GetParent_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_GetCachedGeometry_ReturnValue) == 0x000038, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_GetCachedGeometry_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_GetLocalSize_ReturnValue) == 0x000078, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_GetLocalSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_LocalToViewport_PixelPosition) == 0x000088, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_LocalToViewport_PixelPosition' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_LocalToViewport_ViewportPosition) == 0x000098, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_LocalToViewport_ViewportPosition' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_Multiply_Vector2DVector2D_ReturnValue) == 0x0000A8, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_Multiply_Vector2DVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_BreakVector2D_X) == 0x0000B8, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_BreakVector2D_Y) == 0x0000C0, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast) == 0x0000C8, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_SetWidthOverride_InWidthOverride_ImplicitCast' has a wrong offset!");
static_assert(offsetof(WBP_PalOverallUILayout_C_UpdateCursor, CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast) == 0x0000CC, "Member 'WBP_PalOverallUILayout_C_UpdateCursor::CallFunc_SetHeightOverride_InHeightOverride_ImplicitCast' has a wrong offset!");

}

