#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalRecruite_Test

#include "Basic.hpp"

#include "Pal_structs.hpp"


namespace SDK::Params
{

// Function WBP_PalRecruite_Test.WBP_PalRecruite_Test_C.DisplayPalInfo
// 0x02E0 (0x02E0 - 0x0000)
struct WBP_PalRecruite_Test_C_DisplayPalInfo final
{
public:
	struct FPalIndividualCharacterSaveParameter   DisplayParameter;                                  // 0x0000(0x02E0)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(WBP_PalRecruite_Test_C_DisplayPalInfo) == 0x000008, "Wrong alignment on WBP_PalRecruite_Test_C_DisplayPalInfo");
static_assert(sizeof(WBP_PalRecruite_Test_C_DisplayPalInfo) == 0x0002E0, "Wrong size on WBP_PalRecruite_Test_C_DisplayPalInfo");
static_assert(offsetof(WBP_PalRecruite_Test_C_DisplayPalInfo, DisplayParameter) == 0x000000, "Member 'WBP_PalRecruite_Test_C_DisplayPalInfo::DisplayParameter' has a wrong offset!");

// Function WBP_PalRecruite_Test.WBP_PalRecruite_Test_C.ExecuteUbergraph_WBP_PalRecruite_Test
// 0x0020 (0x0020 - 0x0000)
struct WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalHUDDispatchParameterBase*           CallFunc_GetParam_ReturnValue;                     // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPalHUDDispatchParameter_PalRecruit*    K2Node_DynamicCast_AsPal_HUDDispatch_Parameter_Pal_Recruit; // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test) == 0x000008, "Wrong alignment on WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test");
static_assert(sizeof(WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test) == 0x000020, "Wrong size on WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test");
static_assert(offsetof(WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test, EntryPoint) == 0x000000, "Member 'WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test, CallFunc_GetParam_ReturnValue) == 0x000008, "Member 'WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test::CallFunc_GetParam_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test, K2Node_DynamicCast_AsPal_HUDDispatch_Parameter_Pal_Recruit) == 0x000010, "Member 'WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test::K2Node_DynamicCast_AsPal_HUDDispatch_Parameter_Pal_Recruit' has a wrong offset!");
static_assert(offsetof(WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'WBP_PalRecruite_Test_C_ExecuteUbergraph_WBP_PalRecruite_Test::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

