#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ItemSearch_Filter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ItemSearch_Filter.WBP_ItemSearch_Filter_C
// 0x0020 (0x0450 - 0x0430)
class UWBP_ItemSearch_Filter_C final : public UPalUserWidgetOverlayUI
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_IngameMenu_Chest_Filter_C*         WBP_IngameMenu_Chest_Filter;                       // 0x0438(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class FName>                           CurrentFilterTypes;                                // 0x0440(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void BndEvt__WBP_ItemChest_Preference_WBP_IngameMenu_Chest_Filter_K2Node_ComponentBoundEvent_0_OnClickedAllCheckButton__DelegateSignature();
	void BndEvt__WBP_ItemChest_Preference_WBP_IngameMenu_Chest_Filter_K2Node_ComponentBoundEvent_1_OnClickedCloseButton__DelegateSignature();
	void BndEvt__WBP_ItemChest_Preference_WBP_IngameMenu_Chest_Filter_K2Node_ComponentBoundEvent_2_OnClickedAllUncheckButton__DelegateSignature();
	void BndEvt__WBP_ItemSearch_Filter_WBP_IngameMenu_Chest_Filter_K2Node_ComponentBoundEvent_3_OnClickedApplyButton__DelegateSignature();
	void ExecuteUbergraph_WBP_ItemSearch_Filter(int32 EntryPoint);
	void OnClickedCheck(class FName TypeId, bool bChecked);
	void OnSetup();
	void Setup();

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ItemSearch_Filter_C">();
	}
	static class UWBP_ItemSearch_Filter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ItemSearch_Filter_C>();
	}
};
static_assert(alignof(UWBP_ItemSearch_Filter_C) == 0x000008, "Wrong alignment on UWBP_ItemSearch_Filter_C");
static_assert(sizeof(UWBP_ItemSearch_Filter_C) == 0x000450, "Wrong size on UWBP_ItemSearch_Filter_C");
static_assert(offsetof(UWBP_ItemSearch_Filter_C, UberGraphFrame) == 0x000430, "Member 'UWBP_ItemSearch_Filter_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_ItemSearch_Filter_C, WBP_IngameMenu_Chest_Filter) == 0x000438, "Member 'UWBP_ItemSearch_Filter_C::WBP_IngameMenu_Chest_Filter' has a wrong offset!");
static_assert(offsetof(UWBP_ItemSearch_Filter_C, CurrentFilterTypes) == 0x000440, "Member 'UWBP_ItemSearch_Filter_C::CurrentFilterTypes' has a wrong offset!");

}

