#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalSaveParameterDisplayWidget

#include "Basic.hpp"

#include "WBP_PalSaveParameterDisplayWidget_classes.hpp"
#include "WBP_PalSaveParameterDisplayWidget_parameters.hpp"


namespace SDK
{

// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.Bind Event
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_PalSaveParameterDisplayWidget_C::Bind_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "Bind Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.Calc HP
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_PalSaveParameterDisplayWidget_C::Calc_HP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "Calc HP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.CalcExp
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Level                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   Exp                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsPlayer                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::CalcExp(int32 Level, int64 Exp, bool IsPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "CalcExp");

	Params::WBP_PalSaveParameterDisplayWidget_C_CalcExp Parms{};

	Parms.Level = Level;
	Parms.Exp = Exp;
	Parms.IsPlayer = IsPlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PalSaveParameterDisplayWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PalSaveParameterDisplayWidget_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.DisplaySaveParameter
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPalIndividualCharacterSaveParameterDisplayParameter                                       (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_PalSaveParameterDisplayWidget_C::DisplaySaveParameter(const struct FPalIndividualCharacterSaveParameter& DisplayParameter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "DisplaySaveParameter");

	Params::WBP_PalSaveParameterDisplayWidget_C_DisplaySaveParameter Parms{};

	Parms.DisplayParameter = std::move(DisplayParameter);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.ExecuteUbergraph_WBP_PalSaveParameterDisplayWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::ExecuteUbergraph_WBP_PalSaveParameterDisplayWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "ExecuteUbergraph_WBP_PalSaveParameterDisplayWidget");

	Params::WBP_PalSaveParameterDisplayWidget_C_ExecuteUbergraph_WBP_PalSaveParameterDisplayWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.GetSaveParameter
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FPalIndividualCharacterSaveParameterParameter                                              (Parm, OutParm)

void UWBP_PalSaveParameterDisplayWidget_C::GetSaveParameter(struct FPalIndividualCharacterSaveParameter* Parameter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "GetSaveParameter");

	Params::WBP_PalSaveParameterDisplayWidget_C_GetSaveParameter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Parameter != nullptr)
		*Parameter = std::move(Parms.Parameter);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.Hide
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_PalSaveParameterDisplayWidget_C::Hide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "Hide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetBaseParameter
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MeleeAttack                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ShotAttack                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Defense                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Support                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Speed                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::SetBaseParameter(int32 MeleeAttack, int32 ShotAttack, int32 Defense, int32 Support, int32 Speed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetBaseParameter");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetBaseParameter Parms{};

	Parms.MeleeAttack = MeleeAttack;
	Parms.ShotAttack = ShotAttack;
	Parms.Defense = Defense;
	Parms.Support = Support;
	Parms.Speed = Speed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetElement
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPalElementType                         Type1                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EPalElementType                         Type2                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::SetElement(EPalElementType Type1, EPalElementType Type2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetElement");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetElement Parms{};

	Parms.Type1 = Type1;
	Parms.Type2 = Type2;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetFavorite
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsFavorite                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::SetFavorite(bool IsFavorite)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetFavorite");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetFavorite Parms{};

	Parms.IsFavorite = IsFavorite;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetFoodAmount
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   FoddAmount                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::SetFoodAmount(int32 FoddAmount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetFoodAmount");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetFoodAmount Parms{};

	Parms.FoddAmount = FoddAmount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetGender
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPalGenderType                          GenderType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::SetGender(EPalGenderType GenderType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetGender");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetGender Parms{};

	Parms.GenderType = GenderType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetHP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NowHP                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   MaxHP                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::SetHP(int32 NowHP, int32 MaxHP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetHP");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetHP Parms{};

	Parms.NowHP = NowHP;
	Parms.MaxHP = MaxHP;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetHunger
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  NowHunger                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  MaxHunger                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::SetHunger(double NowHunger, double MaxHunger)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetHunger");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetHunger Parms{};

	Parms.NowHunger = NowHunger;
	Parms.MaxHunger = MaxHunger;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetLevelAndExp
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Level                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   NowExp                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   NextEXP                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  NowExpRate                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::SetLevelAndExp(int32 Level, int64 NowExp, int64 NextEXP, double NowExpRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetLevelAndExp");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetLevelAndExp Parms{};

	Parms.Level = Level;
	Parms.NowExp = NowExp;
	Parms.NextEXP = NextEXP;
	Parms.NowExpRate = NowExpRate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetNickName
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           NickName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::SetNickName(const class FString& NickName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetNickName");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetNickName Parms{};

	Parms.NickName = std::move(NickName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetPassiveSkill
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FName>                     PassiveSkillnameArray                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_PalSaveParameterDisplayWidget_C::SetPassiveSkill(TArray<class FName>& PassiveSkillnameArray)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetPassiveSkill");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetPassiveSkill Parms{};

	Parms.PassiveSkillnameArray = std::move(PassiveSkillnameArray);

	UObject::ProcessEvent(Func, &Parms);

	PassiveSkillnameArray = std::move(Parms.PassiveSkillnameArray);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetRank
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Rank                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::SetRank(int32 Rank)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetRank");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetRank Parms{};

	Parms.Rank = Rank;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetSoulRank
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SoulRank                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PalSaveParameterDisplayWidget_C::SetSoulRank(int32 SoulRank)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetSoulRank");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetSoulRank Parms{};

	Parms.SoulRank = SoulRank;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetupAfterDisplayed
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_PalSaveParameterDisplayWidget_C::SetupAfterDisplayed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetupAfterDisplayed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetWaza
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<EPalWazaID>                      WazaArray                                              (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_PalSaveParameterDisplayWidget_C::SetWaza(TArray<EPalWazaID>& WazaArray)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetWaza");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetWaza Parms{};

	Parms.WazaArray = std::move(WazaArray);

	UObject::ProcessEvent(Func, &Parms);

	WazaArray = std::move(Parms.WazaArray);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.SetWorkSuitability
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// TMap<EPalWorkSuitability, int32>        SuitabilityMap                                         (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_PalSaveParameterDisplayWidget_C::SetWorkSuitability(const TMap<EPalWorkSuitability, int32>& SuitabilityMap)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "SetWorkSuitability");

	Params::WBP_PalSaveParameterDisplayWidget_C_SetWorkSuitability Parms{};

	Parms.SuitabilityMap = std::move(SuitabilityMap);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.UnbindEvent
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_PalSaveParameterDisplayWidget_C::UnbindEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "UnbindEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PalSaveParameterDisplayWidget.WBP_PalSaveParameterDisplayWidget_C.UpdateForPsn
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_PalSaveParameterDisplayWidget_C::UpdateForPsn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PalSaveParameterDisplayWidget_C", "UpdateForPsn");

	UObject::ProcessEvent(Func, nullptr);
}

}

