#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionSettings_ListContentCheckbox

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_OptionSettings_ListContentCheckbox.WBP_OptionSettings_ListContentCheckbox_C
// 0x0048 (0x02C0 - 0x0278)
class UWBP_OptionSettings_ListContentCheckbox_C final : public UUserWidget
{
public:
	class UWBP_PalInvisibleButton_C*              ButtonToggle_PS5;                                  // 0x0278(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalInvisibleButton_C*              ButtonToggle_Steam;                                // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_PalInvisibleButton_C*              ButtonToggle_Xbox;                                 // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPalCheckBox*                           CheckBox_PS5;                                      // 0x0290(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPalCheckBox*                           CheckBox_Steam;                                    // 0x0298(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPalCheckBox*                           CheckBox_Xbox;                                     // 0x02A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_PS5;                                 // 0x02A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_Steam;                               // 0x02B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_Xbox;                                // 0x02B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_OptionSettings_ListContentCheckbox_C">();
	}
	static class UWBP_OptionSettings_ListContentCheckbox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_OptionSettings_ListContentCheckbox_C>();
	}
};
static_assert(alignof(UWBP_OptionSettings_ListContentCheckbox_C) == 0x000008, "Wrong alignment on UWBP_OptionSettings_ListContentCheckbox_C");
static_assert(sizeof(UWBP_OptionSettings_ListContentCheckbox_C) == 0x0002C0, "Wrong size on UWBP_OptionSettings_ListContentCheckbox_C");
static_assert(offsetof(UWBP_OptionSettings_ListContentCheckbox_C, ButtonToggle_PS5) == 0x000278, "Member 'UWBP_OptionSettings_ListContentCheckbox_C::ButtonToggle_PS5' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSettings_ListContentCheckbox_C, ButtonToggle_Steam) == 0x000280, "Member 'UWBP_OptionSettings_ListContentCheckbox_C::ButtonToggle_Steam' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSettings_ListContentCheckbox_C, ButtonToggle_Xbox) == 0x000288, "Member 'UWBP_OptionSettings_ListContentCheckbox_C::ButtonToggle_Xbox' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSettings_ListContentCheckbox_C, CheckBox_PS5) == 0x000290, "Member 'UWBP_OptionSettings_ListContentCheckbox_C::CheckBox_PS5' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSettings_ListContentCheckbox_C, CheckBox_Steam) == 0x000298, "Member 'UWBP_OptionSettings_ListContentCheckbox_C::CheckBox_Steam' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSettings_ListContentCheckbox_C, CheckBox_Xbox) == 0x0002A0, "Member 'UWBP_OptionSettings_ListContentCheckbox_C::CheckBox_Xbox' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSettings_ListContentCheckbox_C, HorizontalBox_PS5) == 0x0002A8, "Member 'UWBP_OptionSettings_ListContentCheckbox_C::HorizontalBox_PS5' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSettings_ListContentCheckbox_C, HorizontalBox_Steam) == 0x0002B0, "Member 'UWBP_OptionSettings_ListContentCheckbox_C::HorizontalBox_Steam' has a wrong offset!");
static_assert(offsetof(UWBP_OptionSettings_ListContentCheckbox_C, HorizontalBox_Xbox) == 0x0002B8, "Member 'UWBP_OptionSettings_ListContentCheckbox_C::HorizontalBox_Xbox' has a wrong offset!");

}

